### ISSUE TITLE
Documentation - Promise / Callback

### ISSUE THREAD

**Issue by jonface** [Mangopay/mangopay2-nodejs-sdk#106]
https://github.com/Mangopay/mangopay2-nodejs-sdk#promise-vs-callback

Instead of 

```
api.Service.method(... , function(data, response, err){
    // Callback method
})

api.Service.method(...).then(function(data, response) {
    // Promise function called
}, function(error) {
    //exception
})
```

I think the promise function line should read,

`api.Service.method(...).then(function(data) {` , 

I don't see the `response` Object. Originally I was using async/await with destructuring and was getting some weird errors, switched to using .then / .catch and noticed `response` was not present. Was calling `.Users.create()` .

Thanks

**Comment by mickaelpois** [comment]
#110 fix this, thanks @paulhristea !
