### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by Felipe-GN** [Mangopay/mangopay2-nodejs-sdk#108]
Runing 'npm run test' the only test that is ran is the tranfers test (it.only on line 64 of tranfers.js). using npm run test the test should run concurrently.

**Comment by paulhristea** [comment]
Hello @Felipe-GN.

Thanks for bringing this up!
It seems like *someone* left the `.only()` instruction after trying to run that test alone... Will unlock all the tests ASAP.

Sorry about that!

**Comment by mickaelpois** [comment]
Fixed by #112, thanks @paulhristea !
