### ISSUE TITLE
Recurring payment / subscription plan

### ISSUE THREAD

**Issue by launay12u** [Mangopay/mangopay2-nodejs-sdk#109]
It would be convenient to be able to set up subscriptions link to a card or a bank account. Make a recurring payment every month or week, see the payment status, be able to raise and also discount.

**Comment by mickaelpois** [comment]
Hello @launay12u !

Thanks for your feedback and your question about Mangopay.
Recurring payment is not a feature we're goind to support at short-term unfortunately.
But you can easily try to register a card / create a mandate on a bankaccount thanks to Mangopay, and code a recurring payment flow easily by doing a Payin every x day / month.

If you need some advice on how to do it safely, feel free to contact our support team :)

Mickaël

**Comment by kierandes** [comment]
@mickaelpois - hello! I'd be interested in learning how to do the recurring payment flow. Its key to a business model I'm doing for a project. Would support have a case study?
