### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by pavlea** [Mangopay/mangopay2-nodejs-sdk#114]
It would be really good if you'd write code examples fro PayIns and Payouts, refunds etc. Not only for creating users.

**Comment by mickaelpois** [comment]
Hi @pavlea and thanks to be a part of our community !
We want to improve our docs very soon, and your idea is a very good one.
We will shortly add:
* Payin example
* Refund example
* Payout example

We're working on it, and I'll keep you posted here.

Mickaël

**Comment by mangomaxoasis** [comment]
Hi @pavlea,
At this stage improvements to the attached doc are on-going.
However you can find examples of these calls in the Postman libraries on our main doc ->
https://docs.mangopay.com/guide/postman-testing
As we as in the > test > services section of the SDK file 
Feel free to contact us for follow up.
Max
