### ISSUE TITLE
Incorrect cardId while creating a card

### ISSUE THREAD

**Issue by DreaMaTiK** [Mangopay/mangopay2-nodejs-sdk#118]
We are actually having an incorrect card ID while creating a card using API.

We first made a call on mango.CardRegistrations.create for asking to create the card using card datas entered by user and then, we call a second time your API adding accessKey & preRegistration datas necessited to definitively create the card like the code below : 

`          mango.CardRegistrations.create({
            'UserId': user.mangoId,
            'Currency': 'EUR'
          }, function(cardRegistrationData) {
            let cardData = {
                "cardNumber": card.number,
                "cardExpirationDate": card.expires.replace('-', ''),
                "cardCvx": card.cvv
              }

              // Configure the request
              let options = {
                url: cardRegistrationData.CardRegistrationURL,
                headers: {'Content-Type': 'application/x-www-form-urlencoded'},
                form: {
                  data: cardRegistrationData.PreregistrationData,
                  accessKeyRef: cardRegistrationData.AccessKey,
                  cardNumber: cardData.cardNumber,
                  cardExpirationDate: cardData.cardExpirationDate,
                  cardCvx: cardData.cardCvx
                }
              }

              request.post(cardRegistrationData.CardRegistrationURL, options, function(err, httpResponse, body) {
                cardRegistrationData.RegistrationData = body
                mango.CardRegistrations.update(cardRegistrationData, function (createdCard) {
                  if(createdCard.ResultCode !== '000000') {
                    extra.popup = notif(createdCard.ResultCode)
                  }

                  card.resultCode = createdCard.ResultCode

                  mango.CardPreAuthorizations.create({
                    AuthorId : user.mangoId,
                    CardId : createdCard.CardId,
                    SecureMode: "FORCE",
                    ExpirationDate : new moment().add(1, 'day').unix(),
                    DebitedFunds : {
                      Currency : 'EUR',
                      Amount : 100
                    },
                    SecureModereturnURL   : config.webUri +'/redirect3ds'
                  }, function(preAuthorization) {
                    if(preAuthorization.ResultCode !== null && preAuthorization.ResultCode !== '000000') {
                      extra.popup = notif(preAuthorization.ResultCode)
                      cb()
                    }

                    card.popupHtml = preAuthorization.SecureModeRedirectURL
                    card.mangoCardId = createdCard.CardId
                    card.preAuthorizationId = preAuthorization.Id
                    user.cards.push(card)

                    user.save(function(err, user){

                      if(err){
                        card.decline(err.message, via)
                        return cb(err)
                      }

                      card = user.card || user.lastCard
                      cb()
                    })
                  })
                })
              })
            })
`

Everything works fine, but sometime we have a strange answer like an incorrect card id created after the call. I haven't catched the API for the moment, but the informations I got to raise this error are the following car ID returned by the API : **670c2821-4c3d-42b2-b6c6-6af152c96647#1529394882**

Then, on the next call using this card ID (payin, payout...) we have this normal answer : 

> One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. { Message: 'One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.',
  Type: 'param_error',
  Id: '670c2821-4c3d-42b2-b6c6-6af152c96647#1529394882',
  Date: 1529394883,
  errors: 
   { CreditedWalletId: 'The value bf37ed15-d896-4aff-befd-1977bffe4200#1528708284 is not valid' } }

The user ID problem seems appear on user creation, when I encapsulate callbacks like mango.Users.Create & mango.Wallets.create, and mango.PayIns.Create on the next callback, everything works fine when I do it again manually (by deleting mango user & card infos from user collection).

**Comment by mickaelpois** [comment]
Hello @DreaMaTiK,

It seems like your request was errored, but error ID was set as a CardID.
I don't know if you're always facing this issue and using the same workaround, please feel free to give us some feedback here.
