### ISSUE TITLE
Create a PayIn

### ISSUE THREAD

**Issue by pavlea** [Mangopay/mangopay2-nodejs-sdk#119]
We are going live now, so I need to finish MangoPay API integration.

I’m really confused now with making a PayIn. After I create a wallet, need to make a PayIn. The confusing part is in your API docs PayIn object is:
https://docs.mangopay.com/endpoints/v2.01/payins#e269_create-a-card-web-payin

In nodejs SDK is:
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/models/PayIn.js

This is inconsistent, SDK model misses a lot of properties. Of course, when I call PayIns.cretae like this:
const payIn = await this.mangopay.models.PayIn({
AuthorId: user.Id,
DebitedFunds: {
Currency: "EUR",
Amount: chargeAmount
},
Fees: {
Currency: "EUR",
Amount: chargeAmount
},
ReturnURL: "bla.com",
CreditedWalletId: userWallet.Id,
CardType: 'MASTERCARD',
Culture: "EN"
})

const userPayIn = await this.mangopay.PayIns.create(payIn)

and it fails. Error: TypeError: this.initialize is not a function

Could you please help with this? Obviously, I’m missing some step here, but don’t know which object to send here. Wallet And UserNatural are created successfully.

**Comment by mickaelpois** [comment]
Hello @pavlea and sorry for the late answer.
You can have a look at [our tests](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/PayIns.js) and [helpers](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/helpers.js) to better understand how to process a Pay-in.

Your call should be something like:
`CreditedWalletId: userWallet.Id,
AuthorId: user.Id,
DebitedFunds: new api.models.Money({
     Amount: chargeAmount,
     Currency: 'EUR'
}),
Fees: new api.models.Money({
    Amount: 0,
    Currency: 'EUR'
}),
PaymentType: 'CARD',
PaymentDetails: new api.models.PayInPaymentDetailsCard({
       CardType: 'CB_VISA_MASTERCARD'
}),
ExecutionType: 'WEB'
})`

Mickaël
