### ISSUE TITLE
Error specifications for input errors

### ISSUE THREAD

**Issue by amangeot** [Mangopay/mangopay2-nodejs-sdk#120]
Hello,
I can't find any specifications for `Error`s thrown in case of bad inputs. For example, when creating a bank account, if an IBAN is not in the right format, an error will be thrown with some fields: `Id`, `Date`, `Message`, `Type`, etc.

Is there any documentation for such errors? What are the fields?

Is there any instance type we could check? Like MangopayInputError?

Thank you,

**Comment by mickaelpois** [comment]
Hello @amangeot,

If I've well understood your request, you're searching for a documentation for all the HTTP 400 erros that could happen on our API.

There's no exhaustive list of these errors available (yet).
But it could be at least a great add to provide to the community our error structure to better handle these messages, and/or maybe enhance the way we're provinding your these infos on all of our SDK's.

I keep this topic open and will keep you poqted about any enhancement done on this.

Thanks a lot for your feedback, very appreciated !

Mickaël

**Comment by mangomaxoasis** [comment]
Hi @amangeot,

The error are described here :
https://docs.mangopay.com/guide/errors

The error handling is via the following :

errorHandler: function(options, err) {
        console.error(options, err);
    }

Regards,
max
