### ISSUE TITLE
Issue when using webpack

### ISSUE THREAD

**Issue by Ahskaniz** [Mangopay/mangopay2-nodejs-sdk#121]
Same as #17 but using Serverless framework.

See whole stacktrace:
<img width="1168" alt="captura de pantalla 2018-07-11 a las 12 01 41" src="https://user-images.githubusercontent.com/2842448/42564877-3ed3f0ea-8502-11e8-9ae2-f636abf3c3af.png">

**Comment by mickaelpois** [comment]
Hello @Ahskaniz,

Thanks a lot for your feedback.
I'm don't know that well webpack and can't provide you a quick answer about your issue.

Any answer from the community will be well appreciated.
On my side, I'll try to find an answer to your question thanks to our technical teammates, and keep your posted here.

Mickaël

**Comment by catacraciun** [comment]
This SDK is meant to be used only server-side, for client-side please use this one: https://github.com/Mangopay/cardregistration-js-kit.
