### ISSUE TITLE
Getting error on creating Legal User 

### ISSUE THREAD

**Issue by PKJCQS** [Mangopay/mangopay2-nodejs-sdk#123]
I got bellow error when i create Business user
![image](https://user-images.githubusercontent.com/28089985/43962753-1e76e884-9cd6-11e8-84de-4f97bf9f4e7c.png)
How i fix this error

**Comment by mickaelpois** [comment]
Hello @PKJCQS,

Could you just provide me your code sample, to know a little bit more about the request you've processed?

Thanks.

Mickaël
