### ISSUE TITLE
Dependency was not found

### ISSUE THREAD

**Issue by MathieuPcz** [Mangopay/mangopay2-nodejs-sdk#126]
Hi guys,

I encounter a problem when installing your skd on vue js. When I run webpack, this error appears: 

`This dependency was not found:* fs in ./node_modules/mangopay2-nodejs-sdk/lib/api.js`

I am using webpack provided by laravel 5.5 and vue js 2

Can you help me please ?

**Comment by mayon7** [comment]
Hi Mathieu ! Have you fixe your problem ? 
Because i have the same ...

**Comment by MathieuPcz** [comment]
Hi, I went around the problem using another package

https://github.com/Mangopay/cardregistration-js-kit

Hope help you

**Comment by mayon7** [comment]
thanks you for your help !
