### ISSUE TITLE
How to use Idempotent-Key in the sdk?

### ISSUE THREAD

**Issue by ntwobike** [Mangopay/mangopay2-nodejs-sdk#130]
How to use the IdempotentKey with the this sdk. For example i want to do a Transfer from wallet to wallet. 
```
const mangopayTransfer = new api.models.Transfer({
            AuthorId: valid_user_id,
            DebitedFunds: debitedFunds,
            Fees: fees,
            DebitedWalletId: valid_wallet_id, //source wallet
            CreditedWalletId: valid_wallet_id, //destination wallet
        });

api.Transfers.create(mangopayTransfer).then((data) => {});
```

**Comment by mickaelpois** [comment]
Hello @ntwobike , does @ifiokjr answer helps you?

We will improve our technical documentation on Q1 2019 to help you having a clear and (very) quicker answer next time.

**Comment by ntwobike** [comment]
@mickaelpois @ifiokjr Will check and let you know
