### ISSUE TITLE
Publish version 1.9.0 to npm registry

### ISSUE THREAD

**Issue by Se7en-IT** [Mangopay/mangopay2-nodejs-sdk#133]
When do you publish version 1.9.0 to NPM registry? Thanks

**Comment by RaisonBlue** [comment]
How about actually doing this publication ? Not doing it makes documentation on README wrong about authentication...

**Comment by mickaelpois** [comment]
Hello everyone,

We're facing some issues on updating our package on npm through Travis automated workflow (successful build on release branch = package update on npm).

I'll move forward on this issue this week to provide you 1.9.0 version on npm.

Mickaël

**Comment by mickaelpois** [comment]
Hello here, we release directly our new 1.10.0 version to npm this week.
Travis automated workflow should always be enhanced, but I'll temporarily update packages manually to provide you updates very quick this time.
