### ISSUE TITLE
Bug with Per_Page attribute using Wallets.getTransactions

### ISSUE THREAD

**Issue by BenjaminDish** [Mangopay/mangopay2-nodejs-sdk#135]
Hello,

I'm trying to get ALL the transactions of a given Wallet. I'm using the appropriate service and get only 10 transactions, which seems to be the default behavior of the API. I tried to use the 'Per_Page' attribute, set to 100 but it doesn't change anything.

Here is my code: 

```
let client = MangoPayApiService.client();
let options = {
    Per_Page: 100,
    Sort: "CreationDate:DESC"
};
let walletId = "123456";
if (walletId != null) {
    let transactions = await client.Wallets.getTransactions(walletId, options);
}
```

Does someone have an idea of what am I doing wrong ?

**Comment by BenjaminDish** [comment]
I found a workaround :

```
let options = {  
    parameters: {
         page: 1,
         per_page: 25      
    }
};
let arrayHooks = await apiMangopay.Hooks.getAll(options);
```

If it could help someone waiting for a fix.

**Comment by Amassou** [comment]
Oo ty so mush u saved my day  :)

**Comment by iulian03** [comment]
Hello @BenjaminDish ,

For pagination you should use the 'page' and 'per_page' parameters, as shown in the Docs (https://docs.mangopay.com/guide/lists-pagination-management)

In your case it would look something like this:

```
let options = {
    page: 1,
    per_page: 100,
    sort: "CreationDate:desc"
};
```
