### ISSUE TITLE
Can't solve 'invalid_client' error on sandbox

### ISSUE THREAD

**Issue by qchantel** [Mangopay/mangopay2-nodejs-sdk#136]
Hello,

I am trying to create a user to test mangopay API on sandbox but I get an 'invalid-client' error.

**My code:**
```
const mangopay = require("mangopay2-nodejs-sdk");
var api = new mangopay({
  // prettier-ignore
  clientId: '[my_client_id]',
  // prettier-ignore
  clientApiKey: '[my_api_key]',
  debugMode: true
});

function createMangoUser() {
  var myUser = new api.models.UserLegal({
    Name: "MangoPay",
    Email: "info@mangopay.com",
    LegalPersonType: "BUSINESS",
    LegalRepresentativeFirstName: "Mango",
    LegalRepresentativeLastName: "Pay",
    LegalRepresentativeEmail: "mango@mangopay.com",
    HeadquartersAddress: new api.models.Address({
      AddressLine1: "4101 Reservoir Rd NW",
      AddressLine2: "",
      City: "Washington",
      Region: "District of Columbia",
      PostalCode: "20007",
      Country: "US"
    }),
    LegalRepresentativeBirthday: 1300186358,
    LegalRepresentativeNationality: "FR",
    LegalRepresentativeCountryOfResidence: "FR",
    Tag: "custom tag"
  });

  api.Users.create(myUser)
    .then(function() {
      console.log(myUser.Name + " user created at " + myUser.CreationDate);
    })
    .catch(err => console.log(err));
}

module.exports = {
  createMangoUser
};

```

**What I already tried:**
- Adding the baseUrl option and setting it to : https://api.sandbox.mangopay.com
- Creating a user with a model or just a raw object (wasn’t sure the problem came from authentification)
- Testing my clientId/API key on this url : https://api.sandbox.mangopay.com/v2/stoquemarket/users/ and replacing the password by my API key. It works and gives me a list of my users (created on the dashboard).
- Cloning the example repo from the official SDK (https://github.com/Mangopay/mangopay2-nodejs-sdk) and testing the example (same error)
- Recreating a sandbox account to get new clientId/API key
- Force my prettier not to transform ‘ into “ around clientId and clientApiKey strings
- Search the web for solutions, I found these two issues but they didn't solve mine:
    - https://github.com/Mangopay/mangopay2-python-sdk/issues/171
    - https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/102
- Contacting mangopay support by mail and phone and they redirected me to GitHub, so here I am!

**Debug log :**
```
{ '0': 'users_createlegals',
  '1':
   { data:
      child {
        Name: 'MangoPay',
        Email: 'info@mangopay.com',
        LegalPersonType: 'BUSINESS',
        LegalRepresentativeFirstName: 'Mango',
        LegalRepresentativeLastName: 'Pay',
        LegalRepresentativeEmail: 'mango@mangopay.com',
        HeadquartersAddress: [Object],
        LegalRepresentativeBirthday: 1300186358,
        LegalRepresentativeNationality: 'FR',
        LegalRepresentativeCountryOfResidence: 'FR',
        Tag: 'custom tag',
        PersonType: 'LEGAL' },
     dataClass: { [Function: child] extend: [Function: extend], __super__: [Object] } } }
{ error: 'invalid_client' }

```

I think the issue with my code might really be trivial but I can't find it (the fact that the error 'invalid_client' is a bit short doesn't help)! Could you help please?

**Comment by qchantel** [comment]
The error has been fixed thanks to Mangopay support by correcting the example given on the createUser.js SDK repo.

It was not an authentification problem apparently but an invalid field that made the api crash, the field in question:

```
    HeadquartersAddress: new api.models.Address({
      AddressLine1: "4101 Reservoir Rd NW",
      AddressLine2: "",
      City: "Washington",
      Region: "District of Columbia",
      PostalCode: "20007",
      Country: "US"
    })
```

By deleting it the api returned a success.

**Comment by Had-rien** [comment]
Hi,
I have the same error using clientApiKey var in the config.
This is the new variable name but in the current release in npm it is stilled called clientPassword. I had trouble finding this information so I'm posting this to save time for others.

**Comment by sergkulikovskyi** [comment]
@Had-rien thank you!
