### ISSUE TITLE
Bug with Per_Page attribute using Hooks.getAll

### ISSUE THREAD

**Issue by Droppix** [Mangopay/mangopay2-nodejs-sdk#137]
Hi,

it is not possible to obtain more than 10 elements?? (api version 1.8.0 -> npmjs)

Here is my code:
```
let arrayHooks = await apiMangopay.Hooks.getAll({
        Page: 1, 
        Per_Page: 25,
        Sort: "CreationDate:DESC"
});
```
Thanks for your solution
Regards

**Comment by dfa1234** [comment]
Need update on this, I can acces more than 10 Per_Page

**Comment by BenjaminDish** [comment]
There's a problem actually, I'm facing the same. Nevertheless, I found a workaround that works :

```
let options = {  
    parameters: {
         page: 1,
         per_page: 25      
    }
};
let arrayHooks = await apiMangopay.Hooks.getAll(options);
```

Hope it helps !

**Comment by julienreszka** [comment]
Documentations should be updated here with pagination parameters
https://github.com/Mangopay/mangopay2-nodejs-sdk
