### ISSUE TITLE
TypeError: fs.readdirSync is not a function [_servicesLoader]

### ISSUE THREAD

**Issue by mayon7** [Mangopay/mangopay2-nodejs-sdk#140]
Hi !
When we want to make : new mangopay() 
It's doesn't work and wh have this error : 

TypeError: fs.readdirSync is not a function
_servicesLoader

Somebody Help ?

**Comment by mickaelpois** [comment]
@mayon7 ,

Do you have any answer to provide about your issue that could be helpful?

Mickaël
