### ISSUE TITLE
deactivate cards

### ISSUE THREAD

**Issue by dfa1234** [Mangopay/mangopay2-nodejs-sdk#141]
I can't find how to deactivate cards in the sdk:
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/docs/Cards.md

**Comment by dfa1234** [comment]
I found a way looking into the code

`mpay.Cards.update({Id: cardId, Active: false}).then(result => {...})`

A function like for the IBAN would be more intuitive, plus it's not documented that `Id` will serve as path.

**Comment by mickaelpois** [comment]
Hello @dfa1234 !

Happy to see you've found by yourself :)

We could add a proper function to deactivate card, but updates available through our API on cards are very limited that we did not feel useful to add dedicated function for it.

But thanks a lot for your feedback, I'll keep it in mind.

Mickaël
