### ISSUE TITLE
Memory Leak because of old node-rest-client

### ISSUE THREAD

**Issue by kimar** [Mangopay/mangopay2-nodejs-sdk#142]
Hi, we're currently experiencing warnings about memory leaks which are all pointing to this issue https://github.com/aacerox/node-rest-client/issues/80 which has been resolved years ago. As the MangoPay SDK is using a relatively old version of `node-rest-client`, I'd like to know if there are any intentions on your side to upgrade to the latest `node-rest-client`?

**Comment by mickaelpois** [comment]
@kimar Thanks for pointing this up.
Some changes seems to be necessary to upgrade our version, we will make it a part of our next SDK version.

**Comment by kimar** [comment]
Thank you Mickael, indeed we had a look at this when pinning down the issue on our side, but we currently don't have the capacities to fix it ourselves, otherwise we'd have come up with a PR for it.
