### ISSUE TITLE
Formulaire PSP

### ISSUE THREAD

**Issue by mayon7** [Mangopay/mangopay2-nodejs-sdk#144]
Bonjour,
Dans votre doc, vous faites référence à un formulaire PSP via l'API lors de la création d'une page de paiement. Mais je ne trouve pas de trace de ce formulaire ? on le trouve où exactement ? 
Est-ce que c'est bien un formulaire de paiement ? 

Merci d'avance,

**Comment by mickaelpois** [comment]
Bonjour @mayon7,

Je suppose que ce dont vous parlez est le formulaire de saisie des informations de carte dans le cadre d'un Payin **Web**. Il faut donc s'assurer que c'est bien ce type de Payin que vous essayez d'instancier.
Une fois le Payin Web instancié (status = CREATED), il suffit de rediriger l'utilisateur vers l'URL fournie via `RedirectURL` pour afficher ce formulaire et "attendre" qu'il saisisse et valide ses informations bancaires, qui mènent si tout se passe bien vers la validation du paiement.

A titre de comparaison, dans le cadre d'un Payin Direct, tout peut se faire uniquement via appel API: enregistrement de la carte / déclenchement & validation du paiement sur cette carte (hors éventuelle saisie du CVV ou du 3DS qui elle se fera par redirection depuis `SecureModeRedirectURL`).

En espérant avoir répondu à la question :)

Mickaël
