### ISSUE TITLE
Question client SDK

### ISSUE THREAD

**Issue by Akta3d** [Mangopay/mangopay2-nodejs-sdk#147]
I see there is an endpoint to upload KYC document in this NodeJs SDK.
But KYC document should not be stored on our server.

Is there a client SDK to upload directly KYC document from browser to MangoPay server ?

KYC documents should not be uploaded to my own server. Otherwise I need upload KYC document with chunk, but storing KYC document on my server is not allowed.

**Comment by mickaelpois** [comment]
Hello @Akta3d and thanks for your question ! (and very sorry for this delay).
There's no client SDK yet (or any helper as we can provide you for card registration).

That's a very good point we could think about.
Yet, you can only send this file as a base64 encoded string and then delete it from your server.

**Comment by Akta3d** [comment]
Thank for your response,
Actually I send KYC document on the server, and the server send the document to MangoPay.
All is done.

But we have user with bad internet connexion and we need chunk these upload.
But I can't store any chunk on my server (We are not allowed).

I understand that there is no client SDK.
Perhaps an enhancement of the server SDK is the possibility to send KYC document chunk by chunk ?
