### ISSUE TITLE
Moving a mandate from Stauts CREATED to SUMBITTED

### ISSUE THREAD

**Issue by Moneezen** [Mangopay/mangopay2-nodejs-sdk#148]
Hi,

I am trying to trigger the switch of the mandate object status from Created to Submitted.
MangoPay returns only a Redirect URL. it expects that the user opens this URL and click on a CONFIRM button.

I am trying to recreate the post request that this CONFIRM button sends.
Has anyone done that before?

Thanks in advance
Roy

**Comment by mickaelpois** [comment]
Hello @Moneezen,
Why do you want to trigger this button on your side ? Testing automation?

Your customer *need* to confirm *itself* this mandate confirmation, as it's a Compliance need.

Mickaël
