### ISSUE TITLE
UpdateNPM package

### ISSUE THREAD

**Issue by QuentinFarizonAfrimarket** [Mangopay/mangopay2-nodejs-sdk#152]
Mangopay NPM package is still at 1.8.0 : https://www.npmjs.com/package/mangopay2-nodejs-sdk

Whereas here on Github version 1.10.0 has been published, and with it the new documentation (including the renaming of clientPassword to clientApiKey)

Could you pusblish a new version on NPM so that the latest version on NPM matches the documentation here ?

**Comment by mickaelpois** [comment]
Hello @QuentinFarizonAfrimarket ,

Sorry for the (huge) delay, but our deployment flow was (and is always broken) due to some changes on NPM side.

I've manually updated it today, 1.10 version is now available on NPM.
