### ISSUE TITLE
UBO Declaration submission impossible

### ISSUE THREAD

**Issue by Tidaren** [Mangopay/mangopay2-nodejs-sdk#157]
I cannot seem to submit a UBO declaration with the SDK, though it works fine with an http request.

- **SDK Version Used:** v1.10.0
- **Reproduce with:**
```javascript
api.UboDeclarations.update(
  USER_ID,
  new api.models.UboDeclaration({
    Id: UBO_DECLARATION_ID,
    Status: api.models.UboDeclarationStatus.ValidationAsked
  })
);
```
- **Error message:**
```javascript
{ Message: 'You can not do this status change on an UBO Declaration',
  Type: 'invalid_action',
  Id: AN_ID,
  Date: 1565109376,
  errors: null }
```
- **Dev mode logging:**
```javascript
[Arguments] {
  '0': 'ubo_declaration_update',
  '1':
   { data: child { Id: 'UBO_DECLARATION_ID, Status: 'VALIDATION_ASKED' },
     path: { userId: USER_ID, declarationId: UBO_DECLARATION_ID } } }
```
- **Works with the following HTTP Request:**
```shell
curl -X PUT \
  https://api.sandbox.mangopay.com/v2.01/CLIENT_ID/users/USER_ID/kyc/ubodeclarations/UBO_DECLARATION_ID \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic TOKEN' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 33' \
  -H 'Content-Type: application/json' \
  -H 'Host: api.sandbox.mangopay.com' \
  -H 'cache-control: no-cache' \
  -d '{
	"Status": "VALIDATION_ASKED"
}'
```

**Comment by Riwak** [comment]
Hello @Tidaren 

In your code sample 

```
api.UboDeclarations.update(
  USER_ID,
  new api.models.UboDeclaration({
    Id: UBO_DECLARATION_ID,
    Status: api.models.UboDeclarationStatus.ValidationAsked
  })
);
```
you are sending an incomplete UboDeclaration object to the API. This is why you got such message. 

You are trying to send 
`{ Id: 'AN_ID', Status: 'VALIDATION_ASKED' }`

API expecting 
```
{ Id: 'AN_ID',
UserId: 'AN_ID',
 CreationDate: 1565166896,
ProcessedDate: null,
 Status: 'VALIDATION_ASKED',
Reason: null,
Message: null,
Ubos: [blablabla] }
```

You should get the complete UboDeclaration before updating it.

Hope it's clear,

Best regards

**Comment by Tidaren** [comment]
Hi @Riwak 

Thanks for the help! I'll try that as soon as possible.

Since the http api only requires the IDs and the Status, I thought it was also the case for the SDK.

**Comment by Tidaren** [comment]
Update:
It still does not work even when first getting the full UboDeclaration, changing the Status and sending it with the `api.UboDeclarations.update` method.

**Comment by Riwak** [comment]
Hello @Tidaren 

About the Ubos field, it's only for UBO Objects. Please find below an example of a complete UboDeclaration with one Ubo in it. 

```
{ 
    Id: 'AN_ID',
    UserId: 'AN_ID',
    CreationDate: 1565182850,
    ProcessedDate: null,
    Status: 'VALIDATION_ASKED',
    Reason: null,
    Message: null,
    Ubos: 
        [ { 
                Id: 'AN_ID',
                CreationDate: 1565182850,
                LastName: 'Michael_Node',
                FirstName: 'John_Node',
                Birthday: 188348400000,
                Nationality: 'FR',
                Address: {
                            "AddressLine1": "Street1",
                            "AddressLine2": "The Loop",
                            "City": "Paris",
                            "Region": "Ile de France",
                            "PostalCode": "75001",
                            "Country": "FR"
                               },
                Birthplace: {
                             "City": "Paris",
                             "Country": "FR"
                               },
                IsActive: true 
            } ],
}
```

Does the object you are trying to send have the same structure?

**Comment by Tidaren** [comment]
Yes it does have the same structure.

**Comment by zoolle** [comment]
@Tidaren could you find a solution as I am running in the same error

**Comment by Tidaren** [comment]
@zoolle Only solution I have is to use a custom http call for this operation instead of using the sdk until the issue is fixed. I didn't have much time to look into why it fails with the sdk.

**Comment by iulian03** [comment]
Hello, @Tidaren .  I am trying to reproduce your issue by sending this object on the Update method:

{
  Id: 'blabla',
  UserId: 'blabla',
  CreationDate: 1584089970,
  ProcessedDate: null,
  Status: 'VALIDATION_ASKED',
  Reason: null,
  Message: null,
  Ubos: [
    {
      Address: [Object],
      Birthplace: [Object],
      Id: 'blabla',
      CreationDate: 1584089970,
      LastName: 'Doe_NodejsSDK',
      FirstName: 'John_NodejsSDK',
      Birthday: 188344800000,
      Nationality: 'FR',
      IsActive: true
    }
  ]
}

It seems to work as it should, the status is updated correctly. Are you still having this issue? If yes, then what status does your UboDeclaration have before updating it?

**Comment by Tidaren** [comment]
@iulian03 Sorry I cannot test it as I'm on other projects now. If it now works, good. We can close the issue then. Could anyone else confirm?
