### ISSUE TITLE
"other Internal Server Error"

### ISSUE THREAD

**Issue by GriffinSauce** [Mangopay/mangopay2-nodejs-sdk#158]
Hi, I'm getting an error `other Internal Server Error` when calling `mangopay.Mandates.create(props);` with the following data (simplified a bit):

```.js
{
  BankAccountId: '67802381',
  Culture: 'NL',
  ReturnUrl: 'http://localhost:3010/listing/abc',
  Tag: 'ABC123',
  MandateType: 'DIRECT_DEBIT',
  ExecutionType: 'WEB'
}
```

I can't see the attempt either in https://dashboard.sandbox.mangopay.com/Transactions/EventsList

Is there any way I can get more information about this or should I start a support ticket with mangopay itself?

**Comment by Riwak** [comment]
Hey @GriffinSauce,

I didn't find this type of error during my tests. Can you try again with this code sample ? Can I see the output result ? 

Thanks in advance,

```
console.log("-----DEBUG-----")
var mandate_test = new Mandate({
      BankAccountId: ibanAccount.Id,
      Culture: 'NL',
      ReturnUrl: 'http://www.my-site.com/returnURL/',
      Tag: 'custom meta',
      MandateType: 'DIRECT_DEBIT',
      ExecutionType: 'WEB'
});

console.log("input : ")
console.log(mandate_test)

api.Mandates.create(mandate_test, function(data){
     mandate = data;
     console.log("--------")
     console.log("output : ")
     console.log(mandate)
     done();
});
```

**Comment by GriffinSauce** [comment]
Hi Riwak, thanks for looking into it. This is the error I originally got:
```
Internal Server Error {
  Message: 'Internal Server Error',
  Type: 'other',
  Id: '4e7d6e06-2d4d-4f11-8f4c-c88dbb851efc#1566293769',
  Date: 1566293770,
}
```

But now I don't get it anymore, without making changes in my code. 🤔Is there a rate limiter perhaps? I did submit quite a lot of them in quick succession while developing/testing.

**Comment by Riwak** [comment]
Hi @GriffinSauce, 

We have indeed a rate limiter. It can be also an incident or connection issue. If you want more details about the rate limiter : https://docs.mangopay.com/guide/rate-limiting.

Have a nice day 😉

**Comment by GriffinSauce** [comment]
@Riwak I'm still hitting this issue. It appears to only happen in some cases but I can't discover which. When I post identical information directly to the REST API though I get the same response, so this module is not to blame. I'll continue with regular technical support.
