### ISSUE TITLE
new Buffer() deprecated in Node.js 10 +

### ISSUE THREAD

**Issue by fjguipen** [Mangopay/mangopay2-nodejs-sdk#161]
Hey there, Im thinking in using your sdk in our web app. I was having a look when I saw that "new Buffer()" is being used in several parts of the code. Any plan on upgrading it?

> The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead. 

https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

Thanks for your work! 
Cheers

**Comment by iulian03** [comment]
Hello

The 'new Buffer()' deprecated constructors will be updated. :)
