### ISSUE TITLE
Respect semver

### ISSUE THREAD

**Issue by saveman71** [Mangopay/mangopay2-nodejs-sdk#163]
Hello!

`v1.9.0` doesn't respect [semantic versioning](https://semver.org/), and introduces a breaking change that should have been in `v2` if semver was respected. Semver is widely used in the js ecosystem so people using packages tend to think it's used by default.

![Selection_064](https://user-images.githubusercontent.com/1615426/64799254-b45e7780-d584-11e9-9807-b41640c02f52.png)

I greatly approve renaming this variable and understand the motivation but a fallback for people still using the previous parameter should have been put in place, to let time to people to upgrade.

Feel free to close this as it's not an "active" issue, but more a general recommendation for the future, and you also don't want people to just pin their deps and thus not enjoying new features.

**Comment by mickaelpois** [comment]
Hello @saveman71 

101% OK with you, big mistake on our side and we have enhance the way we're dealing with updates:
- CHANGELOG.md is now on this repo and will highlight any breaking change to come *before* being live
- Release note will do the same.

Sorry for this again, and thanks for your constructive feedback
