### ISSUE TITLE
Bad practice on deprecations

### ISSUE THREAD

**Issue by ducdigital** [Mangopay/mangopay2-nodejs-sdk#166]
Hello, 

It seems that there was a field change in the sdk package that was breaking on my side when deploy. 

https://github.com/Mangopay/mangopay2-nodejs-sdk/commit/6d4fe8fae216e8cb60c2b89e92498de84cd23c9b

I'd like to talk about the deprecation process in here. I think what you need to do is write in the application log and warn the sdk users that there will be a deprecation soon, and do it in the next release cycle.

Another thing is that you can still accept the old value, and map it to the new value. 

The PR above is consider a very bad practice and I think you should start taking into account deprecation measure and breaking client's application since you are the payment processor.

Thank you

**Comment by mickaelpois** [comment]
Hello,

Yes, there was a bad breaking change management done before.
As I told on many other repositories issues:
- breaking changes will lead to a major version number update
- breaking changes will be highlighted in our changelog.md file
- breaking changes will be highlighted in our release content on Github.
