### ISSUE TITLE
unauthorized_client error in production environment since change of version

### ISSUE THREAD

**Issue by Owtopsy** [Mangopay/mangopay2-nodejs-sdk#167]
**here is the error returned:** 

{"error":"unauthorized_client","error_description":"This account has been temporarily locked for security reasons. Please try again later."}

**here is the initialization for authentication:**

if (process.env.NODE_ENV === "production") {
    api = new mangopay({
        clientId: 'client-id-prod',
        clientApiKey: 'api-key-prod',
        baseUrl: 'https://api.mangopay.com',
    })
}
else {
    api = new mangopay({
        //SANDBOX
        clientId: 'client-id-dev',
        clientApiKey: 'api-key-dev',
    });
}

**actual behavior:**

I have three different environments: a development server, a staging server and a production server.

Since the module version has been updated from version 1.8.0 to version 1.10.0, the authentication and mangopay requests work on the development server and the staging server but not in production.

When I test locally with https://api.mangopay.com it works perfectly.

Is there something else to take into account depending on the servers after updating the module?

**Comment by Riwak** [comment]
Hey @Owtopsy,

Have you tried contacting our mangopay support center with a Client-ID?
https://support.mangopay.com/s/contactsupport?language=fr

They will have more info to give you regarding your problem as it's more an account problem than a sdk one I think.

I'm stay available if needed,

Audouin,

**Comment by Name-less** [comment]
Hello,
I have the same problem on my account, did you find a solution ?
