### ISSUE TITLE
Problems importing the SDK from a Meteor project

### ISSUE THREAD

**Issue by jonathanazulay** [Mangopay/mangopay2-nodejs-sdk#17]
Trying to import the SDK from a Meteor project (with meteor-webpack), for some reason it fails to read the directories

![screen shot 2016-06-21 at 14 32 04](https://cloud.githubusercontent.com/assets/593305/16229426/fea0732a-37bc-11e6-8417-c435af2e7bf9.png)

Maybe using a relative path would work better?

**Comment by lupugabriel1** [comment]
Hello ! Thanks for bringing this up - I will look over the meteor-webpack compatibility. Is there any particularity I need to be aware of in your project ? Also what system are you trying to run on ? Thanks !

**Comment by jonathanazulay** [comment]
@lupugabriel1 I'm running OS X 10.11.5 with Meteor 1.3.2.4. It seems to be a problem with meteor-webpack. (I tried creating a new project without meteor-webpack and it worked.)

**Comment by lupugabriel1** [comment]
I will try to reproduce it locally, maybe I can provide a fix that includes using relative paths for the services loader.

**Comment by yns01** [comment]
Hello,

If it's any help, I managed to import the SDK from a meteor project and make it work.

```
meteor npm install mangopay2-nodejs-sdk --save
meteor npm install --save meteor-node-stubs

/* Mangopay SDK */
import mp2 from 'mangopay2-nodejs-sdk';
let mangoPayApi = new mp2({
  clientId: Meteor.settings.private.mangopay.clientId,
  clientPassword: Meteor.settings.private.mangopay.clientPassword,
  // debugMode: true,
  // Set the right production API url. If testing, omit the property since it defaults to sandbox URL
  // baseUrl: 'https://api.mangopay.com'
});

export { mangoPayApi };
```

**Comment by jonathanazulay** [comment]
@yns01 Thanks but unfortunately installing meteor-node-stubs did not help. The problem is with webpack.

**Comment by hobailey** [comment]
@jonathanazulay sorry for the delay getting back to you. Are you still experiencing this problem?

**Comment by Ahskaniz** [comment]
Hello, I'm having this same issue and not sure how to solve it.
Any suggestion?
