### ISSUE TITLE
ResultCode null when calling payout creation

### ISSUE THREAD

**Issue by Luxioraw** [Mangopay/mangopay2-nodejs-sdk#178]
Hi ! 

I'm using mangopay2-nodejs-sdk version 1.10.0 (also tested with last version to date, that is to say 1.12.0) 

When i'm calling the library to do a payout with Mango, i'm always receiving a ResultCode and ResultMessage to null, even when the payout is a success or even an error. 

On the other end, payin seems to work fine, and ResultCode / ResultMessage are returned correctly.

After the call to the api, i receive the following object :
(IDs are example)
`Id: '0000000',
  Tag: null,
  CreationDate: 00000000,
  AuthorId: '000000000',
  CreditedUserId: null,
  DebitedFunds: { Currency: 'EUR', Amount: 50000},
  CreditedFunds: { Currency: 'EUR', Amount: 50000},
  Fees: { Currency: 'EUR', Amount: 0 },
  Status: 'CREATED',
  ResultCode: null,
  ResultMessage: null,
  ExecutionDate: null,
  Type: 'PAYOUT',
  Nature: 'REGULAR',
  CreditedWalletId: null,
  DebitedWalletId: '00000000',
  PaymentType: 'BANK_WIRE',
  BankAccountId: '00000000',
  BankWireRef: null`

And on Mango side, i have this :
![image](https://user-images.githubusercontent.com/48524554/82054620-7db2a100-96bf-11ea-8fe1-2b5047a4612a.png)

And for a sucessfull payout on mango side : 
![image](https://user-images.githubusercontent.com/48524554/82054778-c1a5a600-96bf-11ea-9c96-9220da4dc6f7.png)

Both are returning ResultCode null and ResultMessage null...

Any ideas ?

**Comment by mangomaxoasis** [comment]
Hi @Luxioraw 

Upon investigation, when we ran the same call we received the following :

![image](https://user-images.githubusercontent.com/66364935/84651209-d321de00-af09-11ea-8018-bd3df996e694.png)

Please let me know if the call still bugs,

Cheers,
Max
