### ISSUE TITLE
problem to create an user profile

### ISSUE THREAD

**Issue by amoungui** [Mangopay/mangopay2-nodejs-sdk#180]
hello, I would like to use mangopay API, but I have problems when creating a user. the mangopay object tells me that the userLegal property does not exist
my source code.
this is the config file:
`var mangopay = require('mangopay2-nodejs-sdk');

exports.api = new mangopay({
    clientId: 'mackiavel007',
    clientApiKey: 'EgceqtPZWOGV1SruVXfHuCJfvWtqiVhCFjBWwjS5voirBef2pR',
    // Set the right production API url. If testing, omit the property since it defaults to sandbox URL
    baseUrl: 'https://api.sandbox.mangopay.com' //'https://api.mangopay.com' this url is for production
});`

this is my controller
`const api = require('../utils/mangopay'); 
const { handler: errorHandler } = require('../middlewares/error');

/**
 * Create natural user or customer
 * @public
 */
exports.created = async (req, res, next) => {
    var myUser = await new api.models.UserLegal({
        Name: 'MangoPay',
        Email: 'info@mangopay.com',
        LegalPersonType: 'BUSINESS',
        LegalRepresentativeFirstName: 'Mango',
        LegalRepresentativeLastName: 'Pay',
        LegalRepresentativeEmail: 'mango@mangopay.com',
        HeadquartersAddress: new api.models.Address({
            AddressLine1: "4101 Reservoir Rd NW",
            AddressLine2: "",
            City: "Washington",
            Region: "District of Columbia",
            PostalCode: "20007",
            Country: "US"
        }),
        LegalRepresentativeBirthday: 1300186358,
        LegalRepresentativeNationality: 'FR',
        LegalRepresentativeCountryOfResidence: 'FR',
        CompanyNumber: 123456789,
        Tag: 'custom tag'
    });
    
    await api.Users.create(myUser).then(function(){
        // Output the created user data to console
        console.log(myUser.Name + ' user created at ' + myUser.CreationDate);
    }, function(error) {
        console.log(error);
    });
}` 
please i need you help. thank's to advance.

**Comment by iulian03** [comment]
Hello @amoungui,

This is what you are doing wrong:
```
exports.api = new mangopay({
clientId: 'mackiavel007',
clientApiKey: 'EgceqtPZWOGV1SruVXfHuCJfvWtqiVhCFjBWwjS5voirBef2pR',
// Set the right production API url. If testing, omit the property since it defaults to sandbox URL
baseUrl: 'https://api.sandbox.mangopay.com' //'https://api.mangopay.com' this url is for production
});
```

Please use `module.exports = new mangopay(...` instead of `exports.api = new mangopay(...`

**Comment by amoungui** [comment]
Thank's for you help
