### ISSUE TITLE
Documentation seems outdated

### ISSUE THREAD

**Issue by yns01** [Mangopay/mangopay2-nodejs-sdk#19]
Hello,

It seems that the documentation is a bit outdated:

https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e41_create-an-iban-bankaccount

To create an IBAN account:

```
Body Parameters :
{
"Tag": "custom meta",
"OwnerAddress": {
"AddressLine1": "1 Mangopay Street",
"AddressLine2": "The Loop",
"City": "Paris",
"Region": "Ile de France",
"PostalCode": "75001",
"Country": "FR"
},
"OwnerName": "Joe Blogs",
"IBAN": "FR3020041010124530725S03383",
"BIC": "CRLYFRPP"
}
```

The type is missing.

From the tests:

```
        var account = {
            OwnerName: user.FirstName + ' ' + user.LastName,
            OwnerAddress: user.Address,
            Type: 'IBAN',
            IBAN: 'FR7618829754160173622224154',
            BIC: 'CMBRFR2BCME'
        };
```

Also about PayOuts:

https://docs.mangopay.com/endpoints/v2.01/payouts#e228_create-a-payout

```
Body Parameters :
{
"Tag": "custom meta",
"AuthorId": "8494514",
"DebitedFunds": {
"Currency": "EUR",
"Amount": 12
},
"Fees": {
"Currency": "EUR",
"Amount": 12
},
"BankAccountId": "14213351",
"DebitedWalletId": "8519987",
"BankWireRef": "invoice 7282"
}
```

The payment type is missing:

`        "PaymentType": 'BANK_WIRE'
`

**Comment by hobailey** [comment]
Hi @yns01, sorry for the delay getting back to you. Infact the `Type` in both cases is carried by the URL, and not required in the body parameters :-)
