### ISSUE TITLE
Typos in the typings file

### ISSUE THREAD

**Issue by williamdes** [Mangopay/mangopay2-nodejs-sdk#199]
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a7bd8e84aee35ae491527b0c5591b9f68bbe736b/typings/index.d.ts#L1324

Copy pasta seems to have been done :smile: 

https://github.com/search?o=desc&q=%22A+desciption+of+the+wallet%22&s=indexed&type=Code

**Comment by mangomaxoasis** [comment]
Hi @williamdes 
thanks fro the heads up
We'll correct it shortly 
Max

**Comment by williamdes** [comment]
Thank you for your quick response, I was motivated to run https://chrome.google.com/webstore/detail/webpage-spell-check/mgdhaoimpabdhmacaclbbjddhngchjik and found 2 more typos from this manual inspection of the results.

https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a7bd8e84aee35ae491527b0c5591b9f68bbe736b/typings/index.d.ts#L2072

https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a7bd8e84aee35ae491527b0c5591b9f68bbe736b/typings/index.d.ts#L3710

**Comment by mangomaxoasis** [comment]
Cool, we'll treat these together

**Comment by SoloJr** [comment]
Hi @williamdes 

Thank you! :) 

Here is the PR corresponding to your issue: [PR](https://github.com/Mangopay/mangopay2-nodejs-sdk/pull/202)

**Comment by williamdes** [comment]
Closed by #202

**Comment by williamdes** [comment]
Hi @mangomaxoasis 
https://docs.mangopay.com/endpoints/v2.01/payouts#e228_create-a-payout is not up to date too.

**Comment by mangomaxoasis** [comment]
OK, we've reopened 
Also William, if you ever have some time, would if be possible to speak with you about some of the issues you've highlighted? 
My email maxime.gavanon@leetchi.com

**Comment by williamdes** [comment]
> OK, we've reopened
> Also William, if you ever have some time, would if be possible to speak with you about some of the issues you've highlighted?
> My email [maxime.gavanon@leetchi.com](mailto:maxime.gavanon@leetchi.com)

Sure, I emailed you.
You can remove your email from here to avoid some spamming ;)

**Comment by mangomaxoasis** [comment]
Closed
