### ISSUE TITLE
Typescript type for MangoPay.kycDocument.SubmitKycDocument

### ISSUE THREAD

**Issue by fredleroy** [Mangopay/mangopay2-nodejs-sdk#209]
Current definition of the MangoPay.kycDocument.SubmitKycDocument is : 
```
interface SubmitKycDocument {
      /**
       * The status of this KYC/Dispute document
       */
      Status: "VALIDATION_ASKED";
      Tag?: string;
    }
```
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/c0cbc7f89474f8fc0c3f3bd7c564b93c2bdbc04b/typings/index.d.ts#L1534

**However method to actually update the document, seems to require object with document Id (which would be consistent with api doc) :** 

```
updateKycDocument: function (userId, kycDocument, callback, options) {
        options = this._api._getOptions(callback, options, {
            path: {
                id: userId,
                documentId: kycDocument.Id
            },
            data: kycDocument,
            dataClass: KycDocument
        });

        return this._api.method('kyc_documents_save', callback, options);
    }
```
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/c0cbc7f89474f8fc0c3f3bd7c564b93c2bdbc04b/lib/services/Users.js#L350

Am i not using this correctly or is this indeed an error with typescript type ?

**Comment by mangomaxoasis** [comment]
Hey @fredleroy 
We'll check

**Comment by mangomaxoasis** [comment]
Par ailleurs, @fredleroy, serait il possible d'échanger à ce sujet, je suis joignable à maxime.gavanon@leetchi.com

**Comment by tgouala** [comment]
Same issue here, I will force the type by casting but a fix would be very welcome.
I guess adding `Id` property to `SubmitKycDocument` should be enough ?
```
    interface SubmitKycDocument {
      /**
       * The status of this KYC/Dispute document
       */
      Status: "VALIDATION_ASKED";
      Id: string;
      Tag?: string;
    }
```

**Comment by mangomaxoasis** [comment]
Hi,
Missing field added here,
https://github.com/Mangopay/mangopay2-nodejs-sdk/pull/211
Note, we'll try to release shortly but cannot guarantee short turn around as other devs in the queue  
Max

**Comment by mangomaxoasis** [comment]
Hey All,
This should be fixed by https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.14.4
Let me know of ongoing issues 
max
