### ISSUE TITLE
how to make "payins/preauthorized/direct/" with mangopay2-nodejs-sdk

### ISSUE THREAD

**Issue by khan-developpement** [Mangopay/mangopay2-nodejs-sdk#218]
I'm trying to make a payment through a CardPreAuthorization. In the documentation, I don't see how to do the "payins/preauthorized/direc /" which is supposed to activate the payment within 7 days of the CardPreAuthorization.

**Comment by mangomaxoasis** [comment]
Hi @khan-developpement 
We're looking into it
Max

**Comment by mangomaxoasis** [comment]
Hi @khan-developpement 

the flow is as follows 

1. Register Card https://docs.mangopay.com/endpoints/v2.01/cards#e177_the-card-registration-object

2. Using `CardId` create preauthorization 
https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e184_create-a-preauthorization

3. Using `PreauthorizationId`create payin 
https://docs.mangopay.com/endpoints/v2.01/payins#e279_create-a-card-preauthorized-payin

The specific payin call is here =>  
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/services/PayIns.js
using `var PayInPaymentDetailsPreAuthorized = require('../models/PayInPaymentDetailsPreAuthorized');`

Let us know if the issue persists
max

**Comment by mangomaxoasis** [comment]
Hi @khan-developpement 
There's a good example in our testing file, line 120
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/PayIns.js

**Comment by khan-developpement** [comment]
Thank you so much. I just tested. It is OK for me.
