### ISSUE TITLE
Update ipAdress to ipAddress

### ISSUE THREAD

**Issue by julien-boucly-needone** [Mangopay/mangopay2-nodejs-sdk#223]
In your code you have write ipAddress with one `d`. 

cf => https://github.com/Mangopay/mangopay2-nodejs-sdk/compare/1.14.4...1.14.5#diff-613eca09763785e29259820d09d9c797766268513b99dbde9d082f8589c1c4b3R99

**Comment by mangomaxoasis** [comment]
Hi @julien-boucly 
we are checking

**Comment by SoloJr** [comment]
https://github.com/Mangopay/mangopay2-nodejs-sdk/pull/226
