### ISSUE TITLE
Unexpected behaviour on Users.update

### ISSUE THREAD

**Issue by cesaramnuel** [Mangopay/mangopay2-nodejs-sdk#224]
When creating a new Natural User, there are some required fields, such as FirstName or LastName. Address is not among them. When updating an existing Natural User, SDK returns an error if no Address field is provided (Address became suddenly mandatory). Example code:

Creating:
`MPAPI.Users.Create({ FirstName: "John", LastName: "Doe", ... }).then(created => created) // No Address field specified`

created: { NaturalUserModel }

Updating:
`MPAPI.Users.update({ FirstName: "Johnny", LastName: "Doedly", ... }) // No Address field specified
    .then(created => created)
    .catch(err => err) // Err shows that "Address" field is missing.`

**Comment by mangomaxoasis** [comment]
@cesaramnuel Looking into it ,
Max

**Comment by cesaramnuel** [comment]
Hi! sure, here's the case we're dealing with:
`const mangopay = require("mangopay2-nodejs-sdk")`
`const MANGOPAY = new mangopay({ clientId: MP_CLIENT_ID, clientApiKey: MP_CLIENT_API_KEY, baseUrl: MP_BASE_URL })`

```
MANGOPAY.Users.getNatural(MPUserID).then(mpUser => {
            mpUser.FirstName = firstName.trim() // Define new FirstName
            mpUser.LastName = lastName.trim() // Define new LastName
// If this Address definition statement is deleted, MANGOPAY with throw an error, saying there are missing fields.
            mpUser.Address = { //! This information is fake, as it has not been provided by our user
                AddressLine1: "Not provided by User",
                City: "Madrid",
                PostalCode: "28036",
                Country: "ES"
            }
// Update Natural User model with new information
            MANGOPAY.Users.update(mpUser)
                .then(updated => {
                    return resolve(buildResponse(true, undefined, updated))
                }).catch(err => {
                    return reject(buildResponse(false, EXTERNAL_SERVER_ERROR, undefined, 500, err))
                })
        })
```

**Comment by SoloJr** [comment]
Hi @cesaramnuel 

I'm working on a fix. The issue is the following:
When the PUT request to update the user is sent, the API (not the node-js sdk) expects an 'updater' object, with everything that changed. 

If you add this line: 

`mpUser.Address = null`

it will update the user. 

This is a workaround, we need to internally discuss for a fix. 

Thanks,
Mircea

**Comment by cesaramnuel** [comment]
Hi @SoloJr 

After trying that workaround you posted, API returns "Internal Server Error":
```
{
    "Message": "Internal Server Error",
    "Type": "other",
    "Id": "5e549f73-8466-41d6-b3c2-6953072d3342#1612947686",
    "Date": 1612947688,
    "errors": null
}
```

Thing is, if we return to the previous configuration, and set the Address field with fake date, it still returns the same type of message:
```
{
    "Message": "Internal Server Error",
    "Type": "other",
    "Id": "c48ed64e-9b38-4a00-b041-a2a3c0ebbe61#1612947838",
    "Date": 1612947839,
    "errors": null
}
```
