### ISSUE TITLE
Please add deactivate bank account.

### ISSUE THREAD

**Issue by ducdigital** [Mangopay/mangopay2-nodejs-sdk#23]
https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e306_deactivate-a-bank-account 

This is in the doc but not in this SDK. Can you please add this function?

Thank you

**Comment by ducdigital** [comment]
Is this sdk unmaintain?

**Comment by hobailey** [comment]
Hey @ducdigital, I'm sorry for the delay. This SDK is very much maintained :-) But it's very new, and we're still catching up with a few of the latest features - we just added the mandates and direct debits a few days ago, and are currently working on the reporting features. Once that's done, we'll get right on to this bank account feature :-)

**Comment by hobailey** [comment]
This has now been resolved with #25 :-)
