### ISSUE TITLE
Missing KycDocument status in typescript ?

### ISSUE THREAD

**Issue by fredleroy** [Mangopay/mangopay2-nodejs-sdk#230]
Hi,

I can't find the value 'OUT_OF_DATE' for [DocumentStatus](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/typings/index.d.ts#L1354) in typescript typings as described in api doc :

DocumentStatus:

CREATED, VALIDATION_ASKED, VALIDATED, REFUSED, OUT_OF_DATE

The Status of the Document

Am i missing out on something or is this an error with the typings ?

Regards

**Comment by fredericdelordm** [comment]
Hello @fredleroy,

Thank you for this suggestion. We are taking of it. I will keep you updated.

Have a nice day,

**Comment by fredericdelordm** [comment]
Hello @fredleroy,

This has been fixed in our latest release : [1.17.0](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.17.0).

Could you please check on your side ?

Have a nice day,
