### ISSUE TITLE
Error getting payout on getTransactions call

### ISSUE THREAD

**Issue by javigines** [Mangopay/mangopay2-nodejs-sdk#231]
From past Wednesday in the call `MANGOPAY.Wallets.getTransactions` in the sandbox environment, some users return the correct payout transactions, and in others not. 

This Saturday we identify this same issue in the production environment.

These two users are from our sandbox environment and have the explained problem.
98757527 - This retrieves the correct payout transaction
98645831 - In this one it doesn't

The SDK version is 1.14.5

**Comment by dduwoyemgp** [comment]
Hello @javigines 
We'll look into it!

**Comment by fredericdelordm** [comment]
Hello @javigines, do you still have the issue ?

**Comment by javigines** [comment]
Thanks for the refresh call @fredericdelordm,

We had this bug waiting in our backlog and we have not reviewed it again until yesterday. Today my team has been taking a look into it and we think we found the problem.

The problem seems not to be a problem from the SDK but from the documentation itself. We have been checking out the documentation from your API calls and the SDK function in particular, and at any point is mentioned that the `GET .../wallets/:WalletId/transactions/ HTTP/1.1` call is paginated.  In the SDK call's options is not included too. 

So it seems that the call is working as intended but with some lack of information.
Thanks for your time.

**Comment by fredericdelordm** [comment]
Hello @javigines,

Thank you for this update. We are going to improve the documentation with this information.

Have a nice day,
