### ISSUE TITLE
Id property seems missing in CardRegistration.update parameter

### ISSUE THREAD

**Issue by tgouala** [Mangopay/mangopay2-nodejs-sdk#235]
Hello mangopay team,

I am using Typescript. It seems not possible to specify the Id of the previously created card registration.
writing
```
mangoPay.CardRegistrations.update({ RegistrationData: "fdfd", Id: "21212"});
```
will raised a compilation error : `Object literal may only specify known properties, and 'Id' does not exist in type 'UpdateCardRegistration'.`

Shouldn't we add this type here ? :
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/3793a734ff66fe02e1577009f6f59851db2d7eb5/typings/index.d.ts#L1716

**Comment by fredericdelordm** [comment]
Hello @tgouala,

Thank you for your contact. We are looking into it.

Have a nice day,

**Comment by miguelx97** [comment]
Hello, I have the same issue.     

```
const token:string = 'data=dsodfjw3890jhd039jr48998jrnfa94dj3092ej033adfj4a';
const card:MangoPay.cardRegistration.UpdateCardRegistration = {
    RegistrationData: token
}
const registrateCard = await this.mangopayApi.CardRegistrations.update(card);
console.log(registrateCard);  
```

The response is:
```
The ressource does not exist {
  Message: 'The ressource does not exist',
  Type: 'ressource_not_found',
  Id: 'das9d83iodw38939diejd0239,
  Date: 1620222120,
  errors: {
    RessourceNotFound: 'Cannot found the ressource CardRegistration with the id=undefined '
  }
}
```

¿What could we do?

Thank you

**Comment by fredericdelordm** [comment]
Hello @miguelx97, I think your issue is actually different. Could you please open a different issue. 

Have a nice day,

**Comment by fredericdelordm** [comment]
Hello @tgouala,

As you can see [here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/CardRegistrations.js#L74), you need to pass the full cardRegistration object.

Let me know if it's help.
