### ISSUE TITLE
Create a Direct-Debit Direct PayIn 

### ISSUE THREAD

**Issue by melops-hh** [Mangopay/mangopay2-nodejs-sdk#240]
Hello,

I want to create a 'Direct-Debit Direct Payin' with the SDK as described on the api [documentation](https://docs.mangopay.com/endpoints/v2.01/payins#e282_create-a-direct-debit-direct-payin).
```
    await api.PayIns.create({
      AuthorId: authorId,
      CreditedUserId: userId,
      CreditedWalletId: walletId,
      DebitedFunds: { Currency: 'EUR', Amount: 500 },
      Fees: { Currency: 'EUR', Amount: 0 },
      MandateId: mandateId,
    });
```
But i get the error:
`No overload matches this call.`

It assumes I want to create a 'CreateBankWireDirectPayIn'. 
There is no overload for DirectDebitDirectPayIn or similar.
Also I can not use PaymentType: 'DIRECT_DEBIT'.

SDK version: `"mangopay2-nodejs-sdk": "^1.16.0"`

Thank you for your help

EDIT: Changed DIRECT-DEBIT to DIRECT_DEBIT

**Comment by fredericdelordm** [comment]
Hello @melops-hh ,

Thank you for reaching us. @SoloJr will answer your question as soon as possible.

Have a nice day,

**Comment by SoloJr** [comment]
Hi @melops-hh 

Please take a look [here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/PayIns.js#L246)

**Comment by fredericdelordm** [comment]
Hello @melops-hh,

I had a look at your last question.

To add the information `MandateId` and `StatementDescriptor` you should add a `PaymentDetails` parameters with a `PayInPaymentDetailsDirectDebitDirect` object (visible in `lib/models/PayInPaymentDetailsDirectDebitDirect.js`). 
You should also set `ExecutionType` to `DIRECT`.

Let me know if it helps.

**Comment by fredericdelordm** [comment]
Hello @melops-hh,

Did you solved your issue (create a 'Direct-Debit Direct Payin') ?

**Comment by thorgas** [comment]
Hi @fredericdelordm, 
I got the same error using Typescript. I think the type for a Direct-Debit Direct Payin is missing. It probably needs to be added here: https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/3793a734ff66fe02e1577009f6f59851db2d7eb5/typings/index.d.ts#L2849
The code from the tests at https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/3793a734ff66fe02e1577009f6f59851db2d7eb5/test/services/Mandates.js#L191 also shows the same error: No overload matches this call.
  The last overload gave the following error.
    Type '"DIRECT_DEBIT"' is not assignable to type '"BANK_WIRE"'

**Comment by melops-hh** [comment]
Hello @fredericdelordm,

thank you for your response. I recognized I forgot to mention that we are using typescript.
I still get the same error message.

**Comment by fredericdelordm** [comment]
Hello @melops-hh, 

Could you have a look at this thread : https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/221.

It might resolve your issue.
