### ISSUE TITLE
Issue when creating new bank account

### ISSUE THREAD

**Issue by nisa10880** [Mangopay/mangopay2-nodejs-sdk#242]
Hello,

I have an issue when trying to create a new bank account. 

```
    try {
      const bankAccount= await api.Users.createBankAccount({
        UserId: organizer.mangoId,
        Type: "IBAN",
        OwnerAddress: {
          AddressLine1: address.street,
          City: address.city,
          Region: address.state,
          PostalCode: address.zipCode,
          Country: address.country
        },
        OwnerName: organizer.profile.firstName + ' ' + organizer.profile.lastName,
        IBAN: "FR7630004000031234567890143",
        BIC: "BNPAFRPP",
      })

      return bankAccount;

    } catch (error) {
      console.log(error);
      throw error;
    }
```

TypeError: Cannot read property 'Type' of undefined
    at child._getBankAccountType (C:\Users\nidha\Project\letsgo\node_modules\mangopay2-nodejs-sdk\lib\services\Users.js:542:25)
    at child.createBankAccount (C:\Users\nidha\Project\letsgo\node_modules\mangopay2-nodejs-sdk\lib\services\Users.js:185:81)
    at MangopayService.createAddBankAccount (C:\Users\nidha\Project\letsgo\dist\src\mangopay\mangopay.service.js:238:54)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async C:\Users\nidha\Project\letsgo\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at async C:\Users\nidha\Project\letsgo\node_modules\@nestjs\core\router\router-proxy.js:9:17

**Comment by fredericdelordm** [comment]
Hello @nisa10880,

Sorry for the late reply.

Please find below an example on how to create a BankAccount for a user

```javascript  
      api.Users.create(john).then(function (data, response) {
            john = data;

            var account = new BankAccount({
                OwnerName: john.FirstName + ' ' + john.LastName,
                OwnerAddress: john.Address,
                Details: new BankAccountDetailsIBAN({
                    IBAN: 'FR7630004000031234567890143',
                    BIC: 'BNPAFRPP'
                })
            });
            api.Users.createBankAccount(john.Id, account).then(function (account) {
                bankAccount = account;
                done();
            });
        })
```

You can find this example in `test/services/BankAccounts.js`
