### ISSUE TITLE
Error createKycPage returning <Buffer >

### ISSUE THREAD

**Issue by miguelx97** [Mangopay/mangopay2-nodejs-sdk#243]
Hello, I'm trying to upload a KYC document with the nodejs SDK, but it's not working. Also I get `<Buffer >` as a unique response. 

This is my code:
```
const base64Image:string = await imageToBase64("/home/miguel/Downloads/bg1.jpg");
console.log(base64Image.substr(0, 120)+'...');

const buffer = Buffer.from(base64Image.substring(base64Image.indexOf(',') + 1));
console.log("Byte length: " + buffer.length);
console.log("MB: " + buffer.length / 1e+6);

const kycDoc:MangoPay.kycDocument.CreateKycPage = {
    File: base64Image
}        
const createKyc = await this.mangopayApi.Users.createKycPage('108042809', '108962006', kycDoc);            
console.log("res", createKyc);
```

Console response:
```
/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/...
Byte length: 464192
MB: 0.464192
res <Buffer >
```

**Comment by fredericdelordm** [comment]
Hello @miguelx97,

As specified in the [documentation](https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page), you don't need to encode your image in base64. The SDK will do it for you.

**Comment by miguelx97** [comment]
Hello @fredericdelordm, thank you for your quickly response.
I tried changing base64Image by the route of the file, but I got:
`The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. .`

Example:
```
const kycDoc:MangoPay.kycDocument.CreateKycPage = {
    File: "/home/miguel/Downloads/bg1.jpg"
}        
const createKyc = await this.mangopayApi.Users.createKycPage('108042809', '108962006', kycDoc);            
console.log("res", createKyc);
```

Then, I changed `this.mangopayApi.Users.createKycPage(kycDoc)` by `this.mangopayApi.Users.createKycPageFromFile('108042809', '108962006', "/home/miguel/Downloads/bg1.jpg")` but I get the same error: `<Buffer >`

Example:
```
const createKyc = await this.mangopayApi.Users.createKycPageFromFile('108042809', '108962006', "/home/miguel/Downloads/bg1.jpg");            
console.log("res", createKyc);
```

**Comment by fredericdelordm** [comment]
Hello @miguelx97,

First of all, I would suggest to use alongside your development the MANGOPAY dashboard to check if the KYC page is correctly updated.

I will let the developers team get back to you.

Have a nice day,

**Comment by miguelx97** [comment]
Thank you, I'm actually using MANGOPAY dashboard to check it. But it's just not working. Any update about it?

Have a nice day

**Comment by SoloJr** [comment]
Hi @miguelx97 

There have been some changes for the KYC Page. As you can see from [this commit](https://github.com/Mangopay/mangopay2-nodejs-sdk/commit/2f08c09f6f5b7b836575ac175e0448d0b94aec73), you need to send a larger files. 

SoloJr

**Comment by SoloJr** [comment]
Hi @miguelx97 

I cannot reproduce your error whatever I do.. 

Can you try to use the .createKycPageFromFile method as described [here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/Users.js#L504)?

**Comment by fredericdelordm** [comment]
Hello @miguelx97,

Do you still have the issue?

**Comment by miguelx97** [comment]
Hello, thank you for your response.
I've tried your suggestion, but it didn't work. I'm testing with these images.

I'm attaching the images that I used to testting:
![fresas](https://user-images.githubusercontent.com/19576128/126028835-6d2ff510-8adc-4309-aa17-ded2cd78ab25.jpg)
![nature](https://user-images.githubusercontent.com/19576128/126028845-896545e0-0c01-4b71-ade0-a9a53fab3585.jpg)


Code:
```
import MangoPay from 'mangopay2-nodejs-sdk';

const mangopayApi = new MangoPay({
    clientId: 'zirkutest',
    clientApiKey: 'xxxxxxxxxxxxxxxxxx'
});

let image:string = '/mnt/0B7E0DCD0765DC06/Programacion/Node/mangopay_tests/src/fresas.jpg'
let userId:string = '110102983';
let kycDocumentId:string =  '111674859';

mangopayApi.Users.createKycPageFromFile(userId, kycDocumentId, image).then(createKycDoc => {
    console.log("res", JSON.stringify(createKycDoc));

})
```


Response:
`res {"type":"Buffer","data":[]}`

Could you test if there is something that is making fail my code? please.

Thank you so much for helping

Regards

**Comment by iulian03** [comment]
Hello.

The request returns 204 - No Content when it's successful, as described in the API Documentation. Meaning that the SDK will return an empty Buffer, which is expected based on the request answer. I reproduced the KYC flow using the Dashboard and it worked. The document was created and i could't ask for validation until i uploaded a page (which confirms that pages are uploaded). After page upload, the validation worked and i could accept the Document from Dashboard. The code i used:

```
api.PayIns.create({
                        PaymentType: "DIRECT_DEBIT",
                        ExecutionType: "DIRECT",
                        AuthorId: createdUser.Id,
                        CreditedUserId: createdUser.Id,
                        CreditedWalletId: createdWallet.Id,
                        DebitedFunds: {Currency: 'EUR', Amount: 500},
                        Fees: {Currency: 'EUR', Amount: 0},
                        MandateId: createdMandate.Id,
                    })
```

**Comment by fredericdelordm** [comment]
@miguelx97 Don't hesitate to use the MANGOPAY Dashboard alongside your development journey
