### ISSUE TITLE
Error Create KYC Page - The file is too small to be readable

### ISSUE THREAD

**Issue by grafaerig** [Mangopay/mangopay2-nodejs-sdk#244]
At the moment I can create KYC Documents, but not KYC pages. 

Code example:
```

 const frontPage = {
      File: '/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEP ERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4e Hh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAFAAYUDASIA AhEBAxEB/8QAHAAAAAcBAQAA',
    } as mangopay.kycDocument.CreateKycPage;
 
    
    await this.mangoApi.Users.createKycPage(
      userId,
      documentId,
      frontPage,
    );
  ```
    
 Throws error:
 `errors: { File: 'The file is too small to be readable' }`
 
 The code didnt change at all since a few months. The error occurres since a few days.
 
 Even the official documentation throws this error:
 https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page
![image](https://user-images.githubusercontent.com/32541809/119008661-aa645d00-b992-11eb-91f0-b140f60d57d5.png)

What can I do?

**Comment by fredericdelordm** [comment]
Hello @grafaerig,

Thank you for reaching us.

Your KYC Document is an IDENTITY_PROOF ? They should be 32kb minimum now : [documentation](https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page).

Let me know if it answer your question,

**Comment by grafaerig** [comment]
@fredericdelordm 
Thank you for your fast answer, good to know. 
It solved the problem, I will close it.
