### ISSUE TITLE
createKycPageFromFile

### ISSUE THREAD

**Issue by studiocodeur** [Mangopay/mangopay2-nodejs-sdk#247]
Hi there, 

I'm receiving a 'FIle does not exist' in the console when calling
Users.createKycPageFromFile

`mangopay_api.Users.createKycPageFromFile(
                  req?.user[0]?.mangopay_id,
                  data?.Id,
                  { File: base64data },
                  function (model) {
                    console.log(model);
                  }
                );`

**Comment by fredericdelordm** [comment]
Hello @studiocodeur,

Just to be sure, are you passing the path to the file or are you encoding the file in base64? 

You don't need to encode the file. The SDK will do it for you.

Have a nice day,

**Comment by studiocodeur** [comment]
Hi @fredericdelordm, 

Quick update.
When running the following code. I receive '<Buffer >' as response?

mangopay_api.Users.createKycPageFromFile(
  req?.user[0]?.mangopay_id,
  data?.Id,
 "./${document?.path}",
     function (model) {
       console.log(model);
 }
);

**Comment by fredericdelordm** [comment]
Hello @studiocodeur,

If you are uploading a KYC, be aware of the minimal size requested for the file : [documentation here](https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page).

To inform our compliance team that your KYC document is ready to be validated, you need to request validation : [documentation here](https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e206_submit-a-kyc-document)

**Comment by studiocodeur** [comment]
@fredericdelordm 

I'm uploading a file of size 152 kb.
Also how can i make a validation call via this sdk? The api call i know.

**Comment by fredericdelordm** [comment]
Hello @studiocodeur,

Sorry for the late reply, you have an exemple here : https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/Users.js#L381

**Comment by fredericdelordm** [comment]
Hello @studiocodeur,

Did you succeed to make the validation call ?

Have a nice day,

**Comment by miguelx97** [comment]
Hello, thank you for your response.
I've tried your suggestion, but it didn't work. I'm testing with these images.

I'm attaching the images that I used to testting:
![fresas](https://user-images.githubusercontent.com/19576128/125157791-32820a00-e16d-11eb-95d9-27dfa2693820.jpg)
![nature](https://user-images.githubusercontent.com/19576128/125157792-33b33700-e16d-11eb-99ed-6f640d4789e6.jpg)


Code:
```
import MangoPay from 'mangopay2-nodejs-sdk';

const mangopayApi = new MangoPay({
    clientId: 'zirkutest',
    clientApiKey: 'xxxxxxxxxxxxxxxxxx'
});

let image:string = '/mnt/0B7E0DCD0765DC06/Programacion/Node/mangopay_tests/src/fresas.jpg'
let userId:string = '110102983';
let kycDocumentId:string =  '111674859';

mangopayApi.Users.createKycPageFromFile(userId, kycDocumentId, image).then(createKycDoc => {
    console.log("res", JSON.stringify(createKycDoc));

})
```


Response:
`res {"type":"Buffer","data":[]}`

Could you test if there is something that is making fail my code? please.

Thank you so much for helping

Regards
