### ISSUE TITLE
Payout Failed in SandBox

### ISSUE THREAD

**Issue by karthikkumar19** [Mangopay/mangopay2-nodejs-sdk#248]
Can't able to make payout in SandBox Environment, it shows " **Blocked due to the Bank Account User's KYC limitations (maximum debited or credited amount reached): 002998**" . How to make payout in testing? i'm using "**FR7630004000031234567890143**" as IBAN Account number , is there any Other Testing Bank Account?  KYC Validation compulsory for Testing Payouts in sandbox?

**Comment by fredericdelordm** [comment]
Hello @karthikkumar19,

We are looking at the issue.

Have a nice day,

**Comment by karthikkumar19** [comment]
No , is neccessary to complete KYC for Testing Process? Is there any Test Document for KYC Verification?

**Comment by fredericdelordm** [comment]
Yes it is necessary. You can put whatever document you want.

During your development, I suggest you to use the [MANGOPAY dashboard](https://dashboard.sandbox.mangopay.com). You will be able to validate your KYC document from [there](https://dashboard.sandbox.mangopay.com/SandboxOperations).

The idea for you is to discover and develop the full workflow. In production, the KYC documents are validated by MANGOPAY Compliance team.

**Comment by karthikkumar19** [comment]
It's Working Thanks @fredericdelordm 

Any other Bank Account available for Testing other than **"FR7630004000031234567890143'** ?

**Comment by fredericdelordm** [comment]
@karthikkumar19 No other IBAN. Could you explain me why would you need a different one ?

**Comment by karthikkumar19** [comment]
I Mean Not only IBAN , any other like US BankAccount ?

**Comment by fredericdelordm** [comment]
We don't provide a US Bank Account for testing. But don't worry, the flow is identical for the payout.

You only need to add first a US Bank Account in MANGOPAY, documentation [here](https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e27_create-a-us-bank-account).
