### ISSUE TITLE
TS type: 3DS2

### ISSUE THREAD

**Issue by hmica** [Mangopay/mangopay2-nodejs-sdk#249]
version api : 1.17.0

Hi,
Is the type updated for 3ds2 ?
on type CreateCardDirectPayIn the new fields BrowserInfo and  IpAddress are missing on my ide.

Thanks in advance,
Mica

**Comment by fredericdelordm** [comment]
Hello @hmica,

Thank you for your feedback. We are going to review this and add these types if they are missing.

Have a nice day,
