### ISSUE TITLE
mangopay.api.Users.deactivateBankAccount missing return data?

### ISSUE THREAD

**Issue by jyb247** [Mangopay/mangopay2-nodejs-sdk#252]
context: typescript + mangopay2-nodejs-sdk v1.19.0
Hi,
`deactivateBankAccount` seems to return `Promise<void>`, although the original MangopayAPI and the API's callback signature seems supporting returning data;
could it be that the `index.d.ts` should say:
 `deactivateBankAccount: TwoArgsMethodOverload<string, string, bankAccount.Data>;`
rather than
 `deactivateBankAccount: TwoArgsMethodOverload<string, string, void>;`
?
best

**Comment by fredericdelordm** [comment]
Hello @jyb247,

We are looking into it.
