### ISSUE TITLE
Add examples matching doc

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Mangopay/mangopay2-nodejs-sdk#253]
Hello,
I'm following the [guide for marketplace](https://docs.mangopay.com/guide/quickstart-marketplace).
It would be super useful to have a example folder (ideally in Typescript) that follows this guide with the same data so we can experiment easily.
Thanks for the good work 🙂

**Comment by fredericdelordm** [comment]
Hello @GrandSchtroumpf, it is planned for this year :).
