### ISSUE TITLE
"Unspecified BankAccount type": add `Type` in `BankAccountDetailsIBAN` model

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Mangopay/mangopay2-nodejs-sdk#254]
When following the [quickstart marketplace](https://docs.mangopay.com/guide/quickstart-marketplace) example I tried to create a BankAccount wiht the following code: 
```typescript
const bankData = new mangopay.models.BankAccountDetailsIBAN({  
  OwnerName: 'Cyrano de Bergerac',
  OwnerAddress: new mangopay.models.Address({
    AddressLine1:'Street 7',
    AddressLine2: '',
    City: 'Paris',  
    Region: 'Ile de Frog',
    PostalCode:'75010',
    Country:'FR'
  }),  
  IBAN: 'FR7630004000031234567890143',
  BIC: 'BNPAFRPP',
  Tag: 'Postman create a bank account'
});
return mangopay.Users.createBankAccount(userId, bankData);
```
Which result of the error `Unspecified BankAccount type`.
After looking at the [`_getBankAccount`](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/services/Users.js#L548) method I realized the `Type` key is missing from the [`BankAccountDetailsIBAN`](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/models/BankAccountDetailsIBAN.js) model.

**Comment by fredericdelordm** [comment]
Hello @GrandSchtroumpf,

I would suggest to use this test as en example : https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/BankAccounts.js#L15

**Comment by fredericdelordm** [comment]
Hello @GrandSchtroumpf ,

Do you still have the issue?

**Comment by GrandSchtroumpf** [comment]
Hello, I'm sorry I'm not using the sdk anymore, I cannot test. You can close it if you want.
