### ISSUE TITLE
[Type Error] Type '"CARD"' is not assignable to type '"BANK_WIRE"'

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Mangopay/mangopay2-nodejs-sdk#255]
I'm trying to create a direct card payment. I tried : 
```typescript
mangopay.PayIns.create({
  ExecutionType: "DIRECT",
  PaymentType: "CARD",
  AuthorId: userId,
  DebitedFunds: {
    Currency: 'EUR',
    Amount: 100
  }, 
  Fees: {  
    Currency: 'EUR',
    Amount: 0
  },
  CreditedWalletId: '',  
  SecureModeReturnURL: 'http://test.com/',
  SecureMode: 'DEFAULT',  
  CardID: card.CardId,  
  StatementDescriptor: 'Payin'
});
```
And I've got this type error: `Type '"CARD"' is not assignable to type '"BANK_WIRE"'`

Then I tried : 
```typescript
const payinData = new mangopay.models.PayInPaymentDetailsCardDirect({
  AuthorId: userId,
  DebitedFunds: {
    Currency: 'EUR',
    Amount: 100
  }, 
  Fees: {  
    Currency: 'EUR',
    Amount: 0
  },
  CreditedWalletId: '',  
  SecureModeReturnURL: 'http://test.com/',
  SecureMode: 'DEFAULT',  
  CardID: card.CardId,  
  StatementDescriptor: 'Payin'
});
mangopay.PayIns.create(payinData);
```
And I've got this type error: `Argument of type 'PayInPaymentDetailsCardDirect' is not assignable to parameter of type 'CreateBankWireDirectPayIn'`.

I thought that maybe it wasn't the right method, but it looks like it's targeting the [right api](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/services/PayIns.js#L43) if payIn object is a `PayInPaymentDetailsCardDirect`. If it's not the right API I'm sorry for the issue.

**Comment by llucie** [comment]
Hi @GrandSchtroumpf,

I faced this kind of issues not a long time ago, here is what worked for me:


```js
mangopay.PayIns.create({
  ExecutionType: "DIRECT" as const,
  PaymentType: "CARD" as const,
  AuthorId: userId,
  DebitedFunds: {
    Currency: 'EUR',
    Amount: 100
  }, 
  Fees: {  
    Currency: 'EUR',
    Amount: 0
  },
  CreditedWalletId: '',  
  SecureModeReturnURL: 'http://test.com/',
  SecureMode: 'DEFAULT' as const,
  CardID: card.CardId,  
  StatementDescriptor: 'Payin'
});
```

(Notice the `as const` keyword).

I let you read this answer on StackOverflow: https://stackoverflow.com/questions/37978528/typescript-type-string-is-not-assignable-to-type

I hope this will solve your problem as well

**Comment by fredericdelordm** [comment]
Hello @GrandSchtroumpf,

Do you still have the error ?
