### ISSUE TITLE
Cannot create UBO with birthplace

### ISSUE THREAD

**Issue by MondayProgrammer** [Mangopay/mangopay2-nodejs-sdk#262]
Hi,

I read in the [documentation](https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1027_create-a-ubo) that providing the birthplace is compulsory to create a UBO, but the SDK's createUbo method (MangoPay.uboDeclaration.CreateUbo) does not accept a Birthplace property.

Is there a way ?

-----
Node v16.3.0
mangopay2-nodejs-sdk v1.19.0

**Comment by MondayProgrammer** [comment]
Thanks for the answer.

My issue is with the createUbo method.
Here is an example : 

`const declaration = await api.UboDeclarations.create(mangopayId);
    const ubo = await api.UboDeclarations.createUbo(
      mangopayId,
      declaration.Id,
      { Birthplace: {} },
    );`

Argument of type '{ Birthplace: any; }' is not assignable to parameter of type 'CreateUbo'.
Object literal may only specify known properties, and 'Birthplace' does not exist in type 'CreateUbo'.

**Comment by fredericdelordm** [comment]
Hello @MondayProgrammer ,

Good catch. I am adding a task right now to fix that.

**Comment by MondayProgrammer** [comment]
Hello @fredericdelordm,

I profit of the occasion, to notify you that [KYC_OUTDATED](https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object) is missing in [EventType](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/372c9fb6d7cfd7389f157457b32d9b16cdead6d2/typings/index.d.ts#L3144).

Have a good day!

**Comment by fredericdelordm** [comment]
Hello @MondayProgrammer, 

I'll register a task for that also.

**Comment by fredericdelordm** [comment]
Hello @MondayProgrammer,

This has been fix in the [last release](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.20.2).

Have a nice day,
