### ISSUE TITLE
Banking Alias - Wallet ID missing in IBANBankingAliasData

### ISSUE THREAD

**Issue by hermann-salto** [Mangopay/mangopay2-nodejs-sdk#264]
Version SDK : 1.20.0
Feature : Create Banking Alias

Hello,
When I create a Banking Alias, The object returned IBANBankingAliasData does not contain Wallet ID. Is there a way to get it. Or can you had this property to IBANBankingAliasData ?
Thank you

**Comment by fredericdelordm** [comment]
Hello @hermann-salto,

Thank you for your feedback.

If you see this test [example](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/BankingAliases.js#L44), you can see that WalletId already exists and is available.

Does it happen every time? Can you see your BankingAlias in your MANGOPAY dashboard?

**Comment by hermann-salto** [comment]
thank you @fredericdelordm, it works !
