### ISSUE TITLE
Recurring PayIns methods not exposed in Typescript types

### ISSUE THREAD

**Issue by belinde** [Mangopay/mangopay2-nodejs-sdk#269]
in `typings/index.d.ts` the definition of class `PayIns` (currently in line 4013 on master) doesn't contains the definitions for these methods:

- `getRecurringPayin`
- `updateRecurringPayin`
- `createRecurringPayment`
- `createRecurringPayInRegistrationCIT`
- `createRecurringPayInRegistrationMIT`
- `getExecutionKey`

**Comment by fredericdelordm** [comment]
Hello @belinde,

Adding this to our sprint. I'll keep you updated

**Comment by fredericdelordm** [comment]
Hello @belinde,

This has been fixed in the [last release](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.20.2).

Have a nice day,
