### ISSUE TITLE
Error createKycPage and createKycPageFromFile returning <Buffer >

### ISSUE THREAD

**Issue by rahou0** [Mangopay/mangopay2-nodejs-sdk#272]
Hello, I'm trying to create a KYC Page with the nodejs SDK, I get <Buffer > as a unique response.

i tried the  TestKycPageFile image with createKycPageFromFile but it still show <Buffer >

`

    var filePath = path.resolve(__dirname, "./TestKycPageFile.png");
     console.log(filePath);
     const page = await api.Users.createKycPageFromFile(
       req.params.id,
       req.params.document_id,
       filePath
     );
    res.status(201).send({ msg: messages.successfully_created, page });
`

KYCPageFileStringNew its the base64 that u are using in the test file

`

    const page = await api.Users.createKycPage(
      req.params.id,
      req.params.document_id,
      { File: KYCPageFileStringNew }
    );
     console.log(page);
    res.status(201).send({ msg: messages.successfully_created, page });

`

**Comment by fredericdelordm** [comment]
Hello @rahou0,

Did you double check in the MANGOPAY dashboard that your kyc page has been created?

**Comment by rahou0** [comment]
@fredericdelordm 
i dont think we can see if the KYC page is create the only think that i can see is the KYC document is created.
if its possible can u show me how?

**Comment by Ironem** [comment]
Hello @fredericdelordm,

I think that you need update your doc in node sdk.
![image](https://github.com/Mangopay/mangopay2-nodejs-sdk/assets/57012015/541ced46-ba44-4ffe-ba98-988f13e8431f)

It mentions that createKycPage return a KycDocumentData but actually the response is empty. To update the doc, we need to put the id and status manually to change the status to "VALIDATION_ASKED".

**Comment by KSanWapiti** [comment]
> Hello @fredericdelordm,
> 
> I think that you need update your doc in node sdk. ![image](https://user-images.githubusercontent.com/57012015/241057381-541ced46-ba44-4ffe-ba98-988f13e8431f.png)
> 
> It mentions that createKycPage return a KycDocumentData but actually the response is empty. To update the doc, we need to put the id and status manually to change the status to "VALIDATION_ASKED".

same here
