### ISSUE TITLE
Web PayIn secure mode: "NO_CHOICE"

### ISSUE THREAD

**Issue by HardikDG** [Mangopay/mangopay2-nodejs-sdk#274]
How can we use secure mode: "NO_CHOICE" when using thie SDK?
As per my discussion with the support team, for future support and better security/liability reduction, we should use "NO_CHOICE" option in the secure mode.

Currently, I am using "DEFAULT" mode in the secureMode option, now if I want to use secureMode: "NO_CHOICE", how can I use it? 
in the index.d.ts it's having 2 options only :(
 type SecureMode = "DEFAULT" | "FORCE";

So when I try to assign value of "NO_CHOICE" it's showing unacceptable value. 
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/12171c46032f6809cf3f3e0f4d8c88824d8fbd19/typings/index.d.ts#L86

**Comment by fredericdelordm** [comment]
Hello @HardikDG,

A fix will be added to the next release (early September).

Have a nice day,

**Comment by fredericdelordm** [comment]
Hello @HardikDG,

This has been fixed. More information in this [release note](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.20.2).
