### ISSUE TITLE
TypeScript: Possible missing types on CardPreAuthorizationData

### ISSUE THREAD

**Issue by soullivaneuh** [Mangopay/mangopay2-nodejs-sdk#278]
According to your [API documentation](https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e184_create-a-preauthorization) we have to add the `IpAddress` and the `BrowserInfo` body parameter of the PreAuthorization data.

However, I don't see it on the typing: https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/6d1443f9701bdedbbb96d1667839f33fb08af09e/typings/index.d.ts#L1827

Is it a missing part like for #249?

**Comment by fredericdelordm** [comment]
Hello @soullivaneuh,

Let me double check. Have a nice day,

**Comment by soullivaneuh** [comment]
Did you find any clue?

**Comment by fredericdelordm** [comment]
Hello @soullivaneuh, it has been added in our latest release.
