### ISSUE TITLE
Instant Payout - No PayoutModeRequested in PayOut.CreatePayOut object

### ISSUE THREAD

**Issue by hermann-salto** [Mangopay/mangopay2-nodejs-sdk#283]
Version SDK : 1.20.2
Feature : Create Instant Payout
Integration in a NestJS (Typescript) backend

Hello,
I would like to create instant payout, unfortunately I do not see  PayoutModeRequested property in CreatePayOut object. So I cannot specify instant payout.
Thank you for your help

**Comment by fredericdelordm** [comment]
Hello @hermann-salto,

We will implement this in the next release.

Have a nice day,
