### ISSUE TITLE
Divergence betwen Type and Documentation For Frequency in Recurring Payments

### ISSUE THREAD

**Issue by hmica** [Mangopay/mangopay2-nodejs-sdk#288]
Hi, 

Frequency  is defined and tested as number but it's [documented](https://docs.mangopay.com/endpoints/v2.01/payins#e1051_create-a-recurring-payin-registration) as a string 

Which one is the correct usage ?

If needed there's a pull request :  #289 

Thanks in advence

**Comment by iulian03** [comment]
Hi, @hmica 

Looks like we missed that, you are right. Thanks for the pull request!
