### ISSUE TITLE
Mandate creation (Typescript) - No MandateType and ExecutionType in CreateMandate interface

### ISSUE THREAD

**Issue by hermann-salto** [Mangopay/mangopay2-nodejs-sdk#291]
Version SDK : 1.20.2
Feature : Create Instant Payout
Integration in a NestJS (Typescript) backend

Hello,

When I try to create mandate with the typescript method mango.Mandates.create  : 

`await this.mango.Mandates.create({
            BankAccountId: mangoBankAccountId,
            Culture: 'FR',
            ReturnURL: returnUrl
        })`

I got an error saying that **ExecutionType** and **MandateType** are missing in the request. 
Unfortunately, the interface **CreateMandate** does not provide these properties.

Is it possible to add 
- ExecutionType: 'WEB'
- MandateType: 'DIRECT_DEBIT'
in the request by default (as these are the only options) or to provide the properties in the CreateMandate interface ?

Thank you for your help

**Comment by fredericdelordm** [comment]
Hello @hermann-salto and @matteobucci, we are going to push within the next two weeks a new version that will handle Typescript perfectly and add missing types.

**Comment by fredericdelordm** [comment]
Hello @hermann-salto, it has been fix in our latest release.
