### ISSUE TITLE
Typescript should be a dev dependency

### ISSUE THREAD

**Issue by javigines** [Mangopay/mangopay2-nodejs-sdk#297]
Hello MangoPay team,

Please change in the package requirements the typescript dependency to a devDependency. Typescript should only be used to compile typescript files into js files. But you are uploading as a requirement to everyone that implements your SDK as a dependency and it supposes around 50MB in size.

Thanks in advance.

**Comment by fredericdelordm** [comment]
Hello @javigines,

Thanks for your feedback. We are reviewing it and we will keep you updated.
