### ISSUE TITLE
Wrong types in Typescript UBO management 

### ISSUE THREAD

**Issue by belinde** [Mangopay/mangopay2-nodejs-sdk#301]
MangoPay.UboDeclarations.updateUbo() expects an UpdateUbo object, but the ID field is not available (the underlying API call is `/users/:UserId/kyc/ubodeclarations/:UboDeclarationId/ubos/:UboId` and the UboId parameter is mandatory).

Interface UboDeclarationData has every property with a `null` type.

**Comment by fredericdelordm** [comment]
Hello @belinde,

Thanks for the feedback. Let us look into it.

Regards and happy new year,

**Comment by fredericdelordm** [comment]
Hello @belinde, I am closing this issue because it has been fixed in 1.25.1
