### ISSUE TITLE
Sort on column with typescript

### ISSUE THREAD

**Issue by LouisGS44** [Mangopay/mangopay2-nodejs-sdk#309]
Hello,

I get a typescript error when i'm trying to add sort parameter : 

```
return await this._api.Users.getCards(userId, {
     parameters: {
          Sort: "CreationDate:DESC"
     }
})
```

Sort parameter is waiting a ColumnAndDirection type : 

`type ColumnAndDirection = "ASC" | "DESC";`

So it's impossible to add column name "CreationDate"

**Comment by fredericdelordm** [comment]
Hello @LouisGS44 ,

We are looking into it.

**Comment by iulian03** [comment]
Hi, @LouisGS44 . This should be fixed now.
