### ISSUE TITLE
Typescript definition for CardPreAuthorizationData does not match api documentation

### ISSUE THREAD

**Issue by fredleroy** [Mangopay/mangopay2-nodejs-sdk#311]
Hi,

Since the introduction of multicapture on preauths, the api documentation states a RemainingFund property on card preauth (https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e183_the-preauthorization-object) but typescript type does not reflect this property (https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/typings/models/cardPreauthorization.d.ts).

Would it be possible to update typings so they reflect the current state of the API ?

Kind regards

**Comment by fredericdelordm** [comment]
Hello @fredleroy, 

We are looking into it.

Have a nice day,

**Comment by fredericdelordm** [comment]
Fix in [1.30.1](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.30.1)
