### ISSUE TITLE
EventData type attribute misspelling

### ISSUE THREAD

**Issue by LouisGS44** [Mangopay/mangopay2-nodejs-sdk#312]
Hello,

There is a misspelling in the EventData type attribute "Ressource".
Here is the type definition : 

```
interface EventData {
   ResourceId: string;
   Date: Timestamp;
   EventType: EventType;
}
```

And here is what the webhook returns : 

```
{
  RessourceId: '139XXXX18',
  EventType: 'PAYIN_NORMAL_SUCCEEDED',
  Date: '1651449600'
}
```

An **S** is missing for ResourceId in the type definition

**Comment by fredericdelordm** [comment]
Hello @LouisGS44, good catch. We are looking into it

**Comment by iulian03** [comment]
Hey @LouisGS44 ,

Is this still an issue? After running the tests I cannot find the double "s" misspelling.

**Comment by LouisGS44** [comment]
Yes it is still an issue. The webhook returns RessourceId with a double "s".

**Comment by fredericdelordm** [comment]
@LouisGS44,

It's due to the MANGOPAY API : https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object.

We will update the API and SDK later
