### ISSUE TITLE
BankAccount Type is not discriminant

### ISSUE THREAD

**Issue by jgabriele** [Mangopay/mangopay2-nodejs-sdk#319]
I think we should use the `BankAccount.Type` property as a discriminant for other props.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/395650/177329625-d0ee0ffb-4ba2-4873-adc2-2e287e560cb1.png">

↑ Here I know that my bankAccount is an `IBANData` but IBAN is not proposed. Worse, if I use it I get an error because `IBAN` does not exist in other BankAccount Types' types.

In the types, `IBANData.Type` is typed as `string | 'IBAN` for example. I guess the `string` part is messing up

**Comment by fredericdelordm** [comment]
Hello @jgabriele,

Thank you for the suggestion, we are looking into it

**Comment by fredericdelordm** [comment]
Fix in [1.30.1](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.30.1)
