### ISSUE TITLE
Promises not rejecting errors

### ISSUE THREAD

**Issue by mdallongeville** [Mangopay/mangopay2-nodejs-sdk#32]
Hello,

The Promises in this SDK are always calling `resolve` even if there is an error. This means that the errors are being ignored unless I explicitely check the result returned or use the errorHandler to log them.

Is it intentional ?

I would rather expect the Promises to `reject` the error so that I could just catch it in my code and stop the execution.

**Comment by gabriellupu** [comment]
Thanks for the update @mdallongeville will double check the exception handler and come back with feedback.

**Comment by gabriellupu** [comment]
@mdallongeville thanks again for your suggestion and for the wait. Once we will merge in #44, Promises will be rejected if the request fails. Let me know how it works after the update. Thanks!
