### ISSUE TITLE
Error catching and Typescript: Object is of type 'unknown'

### ISSUE THREAD

**Issue by soullivaneuh** [Mangopay/mangopay2-nodejs-sdk#320]
Since I upgraded my project to Typescript 4.4+, any catch error is considered as `unknown` and its type has to be verified.

This article well explain the situation: https://bobbyhadz.com/blog/typescript-object-is-of-type-unknown

I have the case with this library. Considering the following code sample:

```typescript
try {
  const mangoCard = await mango.Cards.get(card.cardId);
  // Stuff...
} catch (error) {
  if (error.Type === 'ressource_not_found') {
    // Stuff...
  }

  throw error;
}
```

Gives me the following Typescript error:

```
error TS2571: Object is of type 'unknown'.

208     if (error.Type === 'ressource_not_found') {
            ~~~~~
```

This should be something solvable by using `instanceof` with the right error instance type. For example with a Joi validation error catch:

```typescript
import Joi, {
  ValidationError,
} from 'joi';

try {
  await schema.tailor(context.method).validateAsync(context.data, {
    abortEarly: false,
  });
} catch (e) {
  if (e instanceof ValidationError) {
    throw new BadRequest('invalid data', { errors: e.details });
  }

  throw e;
}
```

However, I did not find any typing representing the MangoPay error containing the `Type` property on this library.

Did I miss something or is it something that need to be updated on that project? :thinking:

**Comment by iulian03** [comment]
Hey @soullivaneuh,

I am going to add an **ApiError** type that should help.

```
type ApiError = {
            Message: string;
            Type: string;
            Id: string;
            Date: number;
            errors: [string, string];
        }
```

Also, you can define your custom error handler when instantiating the API:

```
const api = new mangopay({
    clientId: 'placeholder',
    clientApiKey: 'placeholder',
    errorHandler: function (errorMessage, errorBody: mangopay.models.ApiError) {
        console.log(errorMessage)
        console.log(errorBody)
    }
});
```

**Comment by fredericdelordm** [comment]
Fix in release [1.30.1](https://github.com/Mangopay/mangopay2-nodejs-sdk/releases/tag/1.30.1)

**Comment by soullivaneuh** [comment]
Currently have `1.31.1`, but I don't find the `ApiError` export:

```tsx
import {
  ApiError
} from 'mangopay2-nodejs-sdk';
```

How am I supposed to use it?

**Comment by RodolphePoon** [comment]
> Currently have `1.31.1`, but I don't find the `ApiError` export:
> 
> ```tsx
> import {
>   ApiError
> } from 'mangopay2-nodejs-sdk';
> ```
> 
> How am I supposed to use it?
import * as Mangopay from 'mangopay2-nodejs-sdk';
Mangopay.models.ApiError
