### ISSUE TITLE
Card PayIn with 3DS2

### ISSUE THREAD

**Issue by Ottunger** [Mangopay/mangopay2-nodejs-sdk#326]
MangoPay recently introduced forcefully 3DS2 on all card PayIns.
Does your method support attributes:

```typescript
IpAddress: string;
BrowserInfo: {
    AcceptHeader: string;
    JavaEnabled: boolean;
    Language: string;
    ColorDepth: number;
    ScreenHeight: number;
    ScreenWidth: number;
    TimeZoneOffset: number;
    UserAgent: string;
    JavascriptEnabled: boolean;
}
```

when passed within `PayIns.create`?

**Comment by iulian03** [comment]
Hello @Ottunger,

According to the documentation, only Card Direct PayIns have those properties and yes, you can add them when creating it.

**Comment by Ottunger** [comment]
Cool, seemed to work indeed from testing.
