### ISSUE TITLE
The CreationDate property is missing in the Cards model

### ISSUE THREAD

**Issue by shengdaliu** [Mangopay/mangopay2-nodejs-sdk#332]
HTTP API endpoint results in comparison : 
<img width="875" alt="Screenshot 2022-08-29 at 14 42 43" src="https://user-images.githubusercontent.com/5356482/187203603-5cc4b88f-7b2b-4558-b12b-618f7e32e7f2.png">

https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/af159a907515b1b0760879a837da551888549f33/lib/models/Card.js#L4

**Comment by fredericdelordm** [comment]
Hello @shengdaliu,

Thanks for the PR. We are looking into it

**Comment by iulian03** [comment]
Hello, @shengdaliu . The CreationDate is already present in the parent entity - EntityBase

**Comment by shengdaliu** [comment]
Hello @iulian03 

I tried on both release 1.30.0 (My current version on production) and 1.31.1

The `mangopay.Cards.get()` method doesn't retrieve correctly the CreationDate.
Shall I use another endpoint to do that ? 
It seems a bit redundant to make two API calls to get one object instance.

![Screenshot 2022-10-20 at 13 54 23](https://user-images.githubusercontent.com/5356482/196941605-d8ff6706-6434-4f3d-9c93-1a3072e98b7e.png)

**Comment by iulian03** [comment]
@shengdaliu I've tried reproducing your issue on both JS and TS, but the CreationDate is always returned:

**JS**:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/40763147/199675552-fb6b8131-beaf-4aec-aa9e-a6cedfeeb005.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/40763147/199675590-76e595a0-8ea7-479f-adc3-55531ba28fd0.png">


**TS**:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/40763147/199675936-738e5b37-5947-4e23-b467-207cd62e0bf1.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/40763147/199675978-6c0b0bef-7147-49ea-82c5-c104c9c9de60.png">

**Comment by shengdaliu** [comment]
OK, it's all good, I was using `console.log('%j', card)` and  `logger.info('%j', card)` from Winston. Both formatter `%j` filtered out the CreationDate field.

Thank you.
