### ISSUE TITLE
KYC's DocumentStatus is missing `OUT_OF_DATE` value

### ISSUE THREAD

**Issue by jgabriele** [Mangopay/mangopay2-nodejs-sdk#333]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/395650/187438606-896c3c86-018f-4869-96d4-69a3f17282ab.png">

The `OUT_OF_DATE` value is missing

<img width="224" alt="image" src="https://user-images.githubusercontent.com/395650/187439042-751cd0d5-a963-48fc-a31e-0da57482cee0.png">

Note that I have absolutely no Idea how I got this `OUT_OF_DATE` KYC but as it's a possible case I think it should be part of the type.

**Comment by fredericdelordm** [comment]
Hello @jgabriele, good catch. We will add it in the next release

**Comment by lcallarec** [comment]
Looks like this issue could be closed, missing status was added here: https://github.com/Mangopay/mangopay2-nodejs-sdk/commit/1dc071bb9befbeedd53ff8279c33a5b65aee9ca8
