### ISSUE TITLE
Using Mangopay from localhost

### ISSUE THREAD

**Issue by svenvreenen** [Mangopay/mangopay2-nodejs-sdk#349]
When using the nodejs mangopay SDK, when we try to perform any operation from a local environment (localhost), it blocks the requests to the server (CORS). Showing this error:
 'from origin 'http://localhost:3000/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

We already tried adding 'Access-Control-Allow-Origin': '*' to the HTTP request and it doesn't work, We also used a proxy and nothing. Finally, I tried using an extension to disable CORS in my browser and it also didn't work.

Could you help us with this?

**Comment by fredericdelordm** [comment]
Hi @svenvreenen, it's suppose to be a backend SDK.
