### ISSUE TITLE
EAI_AGAIN error

### ISSUE THREAD

**Issue by zefabgithub** [Mangopay/mangopay2-nodejs-sdk#35]
Hello,

Different API calls (get user cards, get user bank accounts, register card) sometimes give the following error:

`Error: getaddrinfo EAI_AGAIN api.sandbox.mangopay.com:443
    at Object.exports._errnoException (util.js:874:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)`

I am using the sandbox for now and the SDK v1.2.0.

Thank you

**Comment by jonface** [comment]
What version of node are you using? Can you try 6.9.2 ? It looks more like a DNS error than Mango.

**Comment by zefabgithub** [comment]
I will upgrade my node version to 6.9.2 and test again.
Thanks

**Comment by hobailey** [comment]
Hey @zefabgithub, how did you get on with the newer version?

**Comment by zefabgithub** [comment]
No error encountered since the node js update. I continue my tests. Sorry for this late answer

**Comment by gabriellupu** [comment]
Thank you for the confirmation @zefabgithub !
