### ISSUE TITLE
Apple Pay and Google Pay is alredy supported?

### ISSUE THREAD

**Issue by capontebable** [Mangopay/mangopay2-nodejs-sdk#364]
I did not find official documentation, I am looking at the unit tests and they are not running. Are these payments really supported?

Unit tests views
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/PayIns.js#L402
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/PayIns.js#L461

**Comment by fredericdelordm** [comment]
Hello @capontebable,

These are beta features open to some customers. Please contact Mangopay support to get access.
