### ISSUE TITLE
Invalid type for `resolveWithFullResponse` response

### ISSUE THREAD

**Issue by david-kovacs-techmates** [Mangopay/mangopay2-nodejs-sdk#395]
Hi!
If I use `resolveWithFullResponse` I get invalid types for the returned data.

Axios returns `status` attribute, while the `WithResponse` type in the `mangopay2-nodejs-sdk` has `status`:

* https://github.com/axios/axios?tab=readme-ov-file#response-schema
* https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/typings/base.d.ts#L161

**Comment by fredericdelordm** [comment]
Hello @david-kovacs-techmates,

Thanks for the feedback. We are looking into it.
