### ISSUE TITLE
Unhandled Promise Rejection in axios integration

### ISSUE THREAD

**Issue by oscarfersan** [Mangopay/mangopay2-nodejs-sdk#401]
Looks like sdk axios integration do not handle promise rejections in the right way

{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read properties of undefined (reading 'data')",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read properties of undefined (reading 'data')",
        "stack": [
            "TypeError: Cannot read properties of undefined (reading 'data')",
            "    at /opt/nodejs/node_modules/mangopay2-nodejs-sdk/lib/api.js:209:96",
            "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "    at runNextTicks (node:internal/process/task_queues:64:3)",
            "    at listOnTimeout (node:internal/timers:540:9)",
            "    at process.processTimers (node:internal/timers:514:7)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read properties of undefined (reading 'data')",
        "    at file:///var/runtime/index.mjs:1276:17",
        "    at /opt/nodejs/node_modules/@lumigo/tracer/dist/tracer/tracer.js:277:37",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
}

**Comment by fredericdelordm** [comment]
Hello @oscarfersan , we are looking into it
