### ISSUE TITLE
Users.getCards returns only 10 cards

### ISSUE THREAD

**Issue by adrienbarreau** [Mangopay/mangopay2-nodejs-sdk#43]
When I call Users.getCards it only returns the last 10 cards.
How can I get the others ones ?

**Comment by gabriellupu** [comment]
Hello @adrienbarreau ! Here you have an examples for pagination on the `Users.getAll` https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/examples/getUsers.js#L25

In your case should be 
```
// Get 100 users
api.Users. getCards({
    parameters: {
        per_page: 100,
        page: 1
    }
})

// Get 10 users but the second page
api.Users. getCards({
    parameters: {
        per_page: 10,
        page: 2
    }
})
```

**Comment by foramkumarparekh** [comment]
Hey, I am facing the same issue, but I am not getting, exactly where I should pass _parameters_ data.

I am using promise with the API call. Please have a look at my code snippet, for more reference.

> api.Users.getCards(userId).then(function (response) {
            console.log('response');
            console.log(response);
        }, function (error) {
            console.log('mangopay service: error in fetching cards for user');
            console.log(error);
        });
Can you help me, where I can pass the _parameters_ data? Also, what value should I pass to get all the data?

**Comment by paulhristea** [comment]
Hey there @foramkumarparekh!

Please try it like this:
```
api.Users.getCards(userId, _parameters_).then(function (response) {
    console.log(response);
}, function (error) {
    console.log(error);
});
```
You should be able to find data about how many pages are left or maybe how many total items from the response headers such as:
```
console.log(response.headers['x-number-of-pages']);
```
Hope it helps!
