### ISSUE TITLE
Error not caught using promises

### ISSUE THREAD

**Issue by yns01** [Mangopay/mangopay2-nodejs-sdk#45]
Hello,

Using  `"mangopay2-nodejs-sdk": "^1.3.2"`, it seems that when using promises errors are not caught in the catch block:

  ```
  mangoPayApi.CardRegistrations.create({
      "UserId": '12345678',
      "Currency": "EUR",
      "CardType": "CB_VISA_MASTERCARD"
    }).then((aCardRegistration) => {
      console.log('Promise OK');
      // console.log(aCardRegistration);
    }).catch((e) => {
      console.log('Promise failed');
      console.log(e);
    });
```
Since the UserId does not exists, the promise will fail. However, the output is:

```
W20170109-23:03:21.534(1)? (STDERR) The ressource does not exist { Message: 'The ressource does not exist',
W20170109-23:03:21.535(1)? (STDERR)   Type: 'ressource_not_found',
W20170109-23:03:21.535(1)? (STDERR)   Id: 'a04adf4a-6569-44ad-aafd-1f6e23424ca7#1483999401',
W20170109-23:03:21.535(1)? (STDERR)   Date: 1483999402,
W20170109-23:03:21.536(1)? (STDERR)   errors: { RessourceNotFound: 'Cannot found the ressource User with the id=12345678 ' } }
*20170109-23:03:21.538(1)? Promise OK <===
I20170109-23:03:21.538(1)? { Message: 'The ressource does not exist',
I20170109-23:03:21.539(1)?   Type: 'ressource_not_found',
I20170109-23:03:21.540(1)?   Id: 'a04adf4a-6569-44ad-aafd-1f6e23424ca7#1483999401',
I20170109-23:03:21.541(1)?   Date: 1483999402,
I20170109-23:03:21.543(1)?   errors: { RessourceNotFound: 'Cannot found the ressource User with the id=12345678 ' } }
```

It looks like that, not only the catch part is not executed, but the then part is despite the error... Not sure if I am doing something wrong or there's an issue.

Thanks for your support.

**Comment by gabriellupu** [comment]
Thanks for bringing this out @yns01 . We're looking over this issue asap.

**Comment by yns01** [comment]
@gabriellupu , do you think you'll be able to investigate anytime soon ?

**Comment by gabriellupu** [comment]
@yns01 I am actually looking over it as we speak 👍

**Comment by yns01** [comment]
@gabriellupu , any progress on this ?

**Comment by gabriellupu** [comment]
Can you please let me know what version of nodejs are you using? Thanks!

**Comment by yns01** [comment]
Using meteor with node v4.6.1

**Comment by gabriellupu** [comment]
managed to reproduce the issue, adding a stable fix now. thanks again for your feedback!

**Comment by yns01** [comment]
Great, waiting for a fix then!

**Comment by yns01** [comment]
@gabriellupu do you have any idea when a fix will be available ? From the quick tests I ran, it seems that the issue occurs with many of the services when using promises

**Comment by gabriellupu** [comment]
Helklo @yns01 I am working on updating the negative tests - changing a failed http request into a promise failure requires a bunch of updates in that area. Will push the fix in a couple hours. Thanks for the follow-up!

**Comment by gabriellupu** [comment]
@hobailey PR has been opened for this issue - do you want me to release (version bump) ?

**Comment by hobailey** [comment]
Great, thanks @gabriellupu. I'll do a release now, don't worry.
