### ISSUE TITLE
Undefined cardRegistration object

### ISSUE THREAD

**Issue by Yoliser** [Mangopay/mangopay2-nodejs-sdk#49]
Hello everyone,

I'm currently working on a NodeJS API and on a phone application that will use MangoPay for the payment.
The problem I'm having is when I want to init a cardRegistration object to do a PayIn, the object is undefined.

Here is my code :

    var Mangopay = require("mangopay2-nodejs-sdk");
    var mangoPay = new Mangopay({
        clientId: "myClientId",
        clientPassword: "myClientPassword",
        // Set the right production API url. If testing, omit the property since it defaults to sandbox URL
        baseUrl: "https://api.sandbox.mangopay.com"
    });

And then in a test function :

    // Initialize mangoPay.cardRegistration object
    mangoPay.cardRegistration.init({
        cardRegistrationURL: cardRegistrationURL,
        preregistrationData: preregistrationData,
        accessKey: accessKey,
        Id: cardRegistrationId
    });

How can I implement this NodeJS sdk in my API?

Thanks in advance,

**Comment by gabriellupu** [comment]
@Yoliser you might want to try
```
mangoPay.CardRegistrations.create({...})
```
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/docs/README.md

Also you can find more usage examples in CardRegistrations tests:
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/CardRegistrations.js

Let me know how it works, thanks!

**Comment by Yoliser** [comment]
Thanks for the quick reply, but I have another problem now.

`mangoPay.CardRegistrations.create({...})` works, and I receive the data I need. I'm using the "request" module for NodeJS to send PreregistrationData, AccessKey and some other things to the CardRegistrationURL I got.
The thing is, the only thing I receive is 02628 for the error code (so bad url, because I can't use any, it's for a phone application), or http 302 (so bad redirection).

Can you help me for this? Will I be able to register and use the card if I also use the JS Kit (https://github.com/Mangopay/cardregistration-js-kit)? All of work needs to be done in NodeJS, so that any phone application can use it easily.

My code below :

```
mangoPay.CardRegistrations.create({
            "UserId": "20102670",
            "Currency": "EUR",
            "CardType": "CB_VISA_MASTERCARD"
        },
        function (res) {
            var cardRegistrationData = {
                "data": res.PreregistrationData,
                "accessKeyRef": res.AccessKey,
                "returnURL": "url",
                "cardNumber": "4970100000000154",
                "cardExpirationDate": "1019",
                "cardCvx": "123"
            };

            // Set the headers
            var headers = {
                'Content-Type': 'application/x-www-form-urlencoded'
            }

            // Configure the request
            var options = {
                url: res.CardRegistrationURL,
                method: 'POST',
                headers: headers,
                form: cardRegistrationData
            }

            request.post(options,
                function (error, response, body) {
                    console.log("ERROR = " + error);
                    console.log("RESPONSE = %j", response);
                    if (!error) {
                        console.log("BODY = " + body)
                    }
                }
            );
        });
```

I tried the code below instead of using the request module, but I can't change the url, so I think that's not the right way to go.

```
mangoPay.CardRegistrations.update({
            "parameters": {
                "data": cardRegistration.preregistrationData,
                "accessKeyRef": cardRegistration.accessKey,
                "cardNumber": "4706750000000009",
                "cardExpirationDate": "1019",
                "cardCvx": "123"
            },
            "url": cardRegistration.cardRegistrationURL
        },
        function (res) {
            console.log("CARD UPDATE = %j", res);
        });
```

I thank you in advance for your time,

**Comment by gabriellupu** [comment]
I suggest to use the SDK's internal post method that wraps around request.post when custom HTTP calls are needed:

In your case replace
```
request.post(options,
        function (error, response, body) {
            ...
        }
    );
});
```
with
```
mangoPay.method('post', function (data, response) {
...
}, options);
```
If you receive URL errors, please debug reponse.request url value and put the output here. Also the full server error would be helpful. 
Thanks!

**Comment by Yoliser** [comment]
Thanks again for the quick reply.

Just tried it, but only got "Circular" for response and "undefined" for response.request.
I tried putting every data needed in "options", and also tried with the form parameter, 

If you need to see the Circular object, here it is : http://pastebin.com/8a1JXkev
For the data I receive, I only have
`{"type":"Buffer","data":[101,114,114,111,114,67,111,100,101,61,48,57,49,48,49]}"`

See code below :

```
var cardRegistrationData = {
                "data": res.PreregistrationData,
                "accessKeyRef": res.AccessKey,
                "returnURL": "url",
                "cardNumber": "4970100000000154",
                "cardExpirationDate": "1020",
                "cardCvx": "123"
            };

            // Set the headers
            var headers = {
                'Content-Type': 'application/x-www-form-urlencoded'
            }

            // Configure the request
            var options = {
                url: res.CardRegistrationURL,
                method: 'POST',
                headers: headers,
                form: cardRegistrationData
            }

            mangoPay.method('post', function (data, response) {
                console.log("DATA = %j", data);
                console.log("RESPONSE = %j", response);
                console.log(util.inspect(response, {showHidden: false, depth: null}))
                console.log("REQUEST = %j", response.request);
            }, options);
```

I thank you in advance for your time,

**Comment by gabriellupu** [comment]
Hi, thanks for the feedback!
Can you please provide me the whole snippet of code, excepting you credentials? 
Thanks!

**Comment by Yoliser** [comment]
Hi,

Here is the whole code : http://pastebin.com/SVSfNt83.

Thanks,

**Comment by gabriellupu** [comment]
I think what happens there, at like 56, the initial request headers are being overwritten. I need to take a closer look into it. Thanks again for the update!

**Comment by gabriellupu** [comment]
Hello @Yoliser are you still experiencing this issue?

**Comment by Yoliser** [comment]
Hello,
I don't have that problem anymore, because I'm using another payment solution.
But if you have the solution to the issue, you can put it here if peoples in the future need help.

**Comment by gabriellupu** [comment]
Thanks a lot for the quick update @Yoliser . We will further investigate the issue that you described!

**Comment by uditkumawat** [comment]
Did u find the solution ? I am also facing the same issue.

**Comment by gabriellupu** [comment]
Hello @Yoliser, @uditkumawat - can you please try to set the `cardRegistrationData` returnURL to a valid format and override the `Authorization` header:
```json
"returnURL": "http://localhost/",
"Authorization": ""
```
If this will fix your request, I will implement a fix to exclude `Authorization` header from the request to payline card authorization.

Thanks a lot for your feedback!

**Comment by uditkumawat** [comment]
What values should we send in returnUrl parameter and Authorization keys ?

as such I dont have returnUrl... I am only adding card from request module API from backend.

**Comment by gabriellupu** [comment]
Hello @uditkumawat , in the related issue #63 I noticed you have the following objects sent to the server:
```
let cardRegistrationData={
                "data": res.PreregistrationData,
                "accessKeyRef": res.AccessKey,
                "returnURL": "localhost",
                "cardNumber": "4970100000000154",
                "cardExpirationDate": "1020",
                "cardCvx": "123"
            };

  // Set the headers
            var headers = {
                'Content-Type': 'application/x-www-form-urlencoded'
            }

```
I need you to update the variables to:
```
let cardRegistrationData={
                "data": res.PreregistrationData,
                "accessKeyRef": res.AccessKey,
                "returnURL": "http://localhost/",
                "cardNumber": "4970100000000154",
                "cardExpirationDate": "1020",
                "cardCvx": "123"
            };

  // Set the headers
            var headers = {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Authorization': ''
            }

```
Please let me know if it works properly. Thanks!

**Comment by uditkumawat** [comment]
still not working....

**Comment by gabriellupu** [comment]
Here is a complete example that uses `request` library:

```javascript
var mangopay = require("mangopay2-nodejs-sdk");
var request = require('request');

var mangoPay = new mangopay({
    clientId: 'sdk-unit-tests',
    clientPassword: 'cqFfFrWfCcb7UadHNxx2C9Lo6Djw8ZduLi7J9USTmu8bhxxpju'
});

mangoPay.Users.create({
    "PersonType": "NATURAL",
    "Email": "support@mangopay.com",
    "KYCLevel": "REGULAR",
    "FirstName": "Joe",
    "LastName": "Blogs",
    "Birthday": 1463496101,
    "Nationality": "GB",
    "CountryOfResidence": "FR"
}).then(function(userData){
    mangoPay.CardRegistrations.create({
        UserId: userData.Id,
        Currency: "EUR",
        CardType: "CB_VISA_MASTERCARD"
    }).then(function(cardRegistrationData){
        /**
         * This data needs to be securely passed by the user
         * It's strongly recommended to use JS / Android / iOS Card Kits
         */
        var cardData = {
            "cardNumber": "4970100000000154",
            "cardExpirationDate": "1020",
            "cardCvx": "123"
        };

        var headers = {
            'Content-Type': 'application/x-www-form-urlencoded'
        };

        // Configure the request
        var options = {
            url: cardRegistrationData.CardRegistrationURL,
            headers: headers,
            form: {
                data: cardRegistrationData.PreregistrationData,
                accessKeyRef: cardRegistrationData.AccessKey,
                cardNumber: cardData.cardNumber,
                cardExpirationDate: cardData.cardExpirationDate,
                cardCvx: cardData.cardCvx
            }
        };

        request.post(options, function(err, httpResponse, body){
            cardRegistrationData.RegistrationData = body;
            mangoPay.CardRegistrations.update(cardRegistrationData, function(data){
                console.log("Updated card registration is %j", JSON.stringify(data));
            });
        });
    });
});
```
It's very important to understand that customer-sensitive data (card details) should not go trough your own server, instead - you should use the JS / Android / iOS Card Kits. Let me know if this example helps.
