### ISSUE TITLE
add typings file definitions for typescript

### ISSUE THREAD

**Issue by florent1933** [Mangopay/mangopay2-nodejs-sdk#52]
I use this sdk in a typescript project and it would be great if you can provide a typings file.

**Comment by gabriellupu** [comment]
Sorry I accidentally closed the issue. @florent1933 that sounds like something that we totally want to do! Will increase the quality of the SDK!

**Comment by florent1933** [comment]
@gabriellupu awesome! It's a great news and thanks for your quick reply.

**Comment by mmmaxi** [comment]
Is there any Update on this?

**Comment by dfa1234** [comment]
+1 Need update on this

**Comment by PetrBrabec** [comment]
Any news?

**Comment by dfa1234** [comment]
I made a file by myself but I'm not a typescript expert, maybe it should be review. I would like to publish it on github, I'm not sure how to provide it (pull request / new repo, gist?)

**Comment by yacineblr** [comment]
Always nothing ?

**Comment by ifiokjr** [comment]
I'm in the middle of creating some typings (#132) for the project. It probably won't be complete for another few days at least.

**Comment by ifiokjr** [comment]
### Update

I've almost finished creating the types. I'll test it out in my own project over the coming week, tidy up any rough edges and push up the final code. My target is to have it ready for next Friday. 

I've structured it in a way that if the PR takes a while to be merged it can be moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and installed via `yarn add -D @types/mangopay2-nodejs-sdk`.

There's a few caveats and limitations which I've outlined in PR #132. If you see anything that feels wrong I'm happy to listen to suggestions and I'll make amendments where required.

**Comment by nemcek** [comment]
Hey @ifiokjr thank you for doing this!

As the PR is taking a while to be merged already, do you think the types could be moved to DefinitelyTyped for the time being?

**Comment by ifiokjr** [comment]
@nemcek I've opened a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32050

**Comment by StubyProjects** [comment]
Is this working now ?
