### ISSUE TITLE
Getting Response with promise ?

### ISSUE THREAD

**Issue by mickz18** [Mangopay/mangopay2-nodejs-sdk#54]
Hi,

For multi-pages request I want to have access on header params.
I was using promise but I think there is someting wrong with this line 

[`resolve(data, response);`](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/api.js#L210) on api.js 

Does Promise can handle multiple resolve value ?
also I don't see any test using response value.

for now I can use callback and I cannot resolve this without breaking existing code, maybe with an additional parmeter.
{ parameters: { returnResponse : true} } will produce => resolve({data, response});

Thanks,

Mica

**Comment by gabriellupu** [comment]
Hi @mickz18 !
First of all thanks a lot for you feedback, it's very valuable for us in order to improve our SDK! 
Would you mind providing us a comprehensive snippet of code with your case for a better understanding / action to improve your requirement? 

Thanks!

**Comment by mickz18** [comment]
Hi,

this is the change I made on my fork 

https://github.com/Mangopay/mangopay2-nodejs-sdk/compare/master...mickz18:master

so I can use it like this on my code :

`        let mangoUsers = [];
        let currentPage = 0;
        let per_page = 100;
        let number_of_page = 1;
        while (currentPage < number_of_page) {
            let usersWithResponse = await api.Users.getAll({parameters: {per_page: per_page, returnResponse: true}});
            number_of_page = usersWithResponse.response.headers['x-number-of-pages'];
            mangoUsers = [...mangoUsers, ...usersWithResponse.data];
            currentPage++;
        }
        return mangoUsers;`

Of course I will change it to handle page browsing from my admin interface later but I will still need access to the response header.

**Comment by gabriellupu** [comment]
```javascript
getAll: function(callback, options) {
  return this._api.method('users_all', callback, options);
},
```
the Users.getAll function accepts a callback followed by options. In your case, with no SDK changes, we can call it like this if we want to read the header values:

```javascript
api.Users.getAll(function(data, response){
    let number_of_page = response.headers['x-number-of-pages'];
}, {
    parameters: {
        per_page: 1
    }
});
```

**Comment by gabriellupu** [comment]
Apparently the problem with [passing multiple arguments to `onFulfilled()`](http://stackoverflow.com/questions/22773920/can-promises-have-multiple-arguments-to-onfulfilled) was already raised.
One of the indicated solutions would be to use [request-promise](https://www.npmjs.com/package/request-promise#get-the-full-response-instead-of-just-the-body) library, in order to get the full response instead of just the body. Ex:
```javascript
var options = {
    method: 'DELETE',
    uri: 'http://my-server/path/to/resource/1234',
    resolveWithFullResponse: true    //  <---  <---  <---  <--- 
};
 
rp(options)
    .then(function (response) {
        console.log("DELETE succeeded with status %d", response.statusCode);
    })
```
The issue is that we are doing all the requests trough `node-rest-client` library, and the control over the request object is limited.

I like the idea of your solution, but I would like to to keep the code consistent with the other popular way of getting the response as argument for the callback.
```javascript
api.Users.getAll(function (response) {
  // Read pages count
  console.log(response.headers['x-number-of-pages']);

  // Read body
  console.log(response.body);
}, {
  parameters: {
    per_page: 1
  },
  resolveWithFullResponse: true
});
```

**Comment by gabriellupu** [comment]
After merging in the opened pull request and releasing the version, you will be able to use it in your case like:
```javascript
let mangoUsers = []; 
let currentPage = 0; 
let per_page = 100; 
let number_of_page = 1; 
while (currentPage < number_of_page) { 
    let usersWithResponse = await api.Users.getAll({
        parameters: {
            per_page: 
        },
        resolveWithFullResponse: true
    }).then((response) => {
        number_of_page = response.headers['x-number-of-pages'];
        mangoUsers= [...mangoUsers, response.body];
    }); 
    
    currentPage++; 
} 
return mangoUsers;
```
