### ISSUE TITLE
Specifying currency with the new eMoney endpoint

### ISSUE THREAD

**Issue by overture8** [Mangopay/mangopay2-nodejs-sdk#57]
I'm not quite sure how to specify the "currency" for the new eMoney endpoint. I'm using this test as a reference (https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/f42c9a012e4fa9711aecd9c4f3373d42cd2efb53/test/services/EMoney.js#L10). I understand that I'm probably using something that isn't quite finished yet - so maybe I should hold off?

**Comment by mickaelpois** [comment]
Hi @overture8 !

You can not specify what is the currency of EMoney for a particular user, if that's the question.

We use EUR currency as a basis, and every EMoney values that are stored/calculated on our side are in EUR.
You can just get EMoney values for a user in every currencies that are supported by Mangopay, thanks to this GET endpoint: https://docs.mangopay.com/endpoints/v2.01/user-emoney#e894_the-user-emoney-object.

Hope it will be helpful !

**Comment by overture8** [comment]
Hey Mickaël,

Thanks for the quick response! I'm not sure if I'm understanding correctly. Basically, I want to make use of the eMoney endpoint you mentioned above - but I want to use it via the node.js library. The only issue is that I can't figure out how to specify the `Currency` parameter (specified here: https://docs.mangopay.com/endpoints/v2.01/user-emoney#e895_view-a-users-emoney) in order to get the endpoint to return the debits/credits in `GBP`.

Maybe I'm misunderstanding :)

**Comment by mickaelpois** [comment]
Hi again @overture8,

OK that is just a technical issue with nodejs SDK !
I guess @gabriellupu will give you an answer ASAP :)

**Comment by gabriellupu** [comment]
Hello @overture8 ! In order to pass the Currency param along with your request, you can do the following:

```javascript
api.Users.getEMoney(john.Id, null, {
    parameters: {
        Currency: "USD"
    }
}).then(function(data){
   // Process data via promise
});

// -------------- OR

api.Users.getEMoney(john.Id, function() { 
  // Process data via callback 
}, {
    parameters: {
        Currency: "USD"
    }
});
```

You can find more details here: https://github.com/Mangopay/mangopay2-nodejs-sdk#pagination--filtering

Thanks for bringing this out!

**Comment by overture8** [comment]
Many thanks - I'll give this a try now. Do you know when this feature will make it into an npm release?

**Comment by gabriellupu** [comment]
@overture8 the current stable release should support this already!

Thanks!

**Comment by overture8** [comment]
Hey @gabriellupu. I might be missing something - but 1.4.0 doesn't seem to have the `MangoPay.Users.getEMoney` function available. It doesn't seem to be in the code on the v1.4.0 tag on github. Is 1.4.0 the latest version?

**Comment by mickaelpois** [comment]
@overture8 You're totally right, EMoney was not live in 1.4.0 version !
We just try to do some monthly versioning, so I will release a 1.4.1 version this afternoon, containing EMoney support, which was added this month on this SDK.

**Comment by overture8** [comment]
Perfect, thanks.

**Comment by overture8** [comment]
Hi @mickaelpois - sorry for bothering you with this. Can you let me know when 1.4.1 is release on npm? I just want to get this code integrated into something I'm working on currently.

Thanks :)

**Comment by mickaelpois** [comment]
@overture8 We're experiencing some issues with auto deployment on npm, we're looking at this right now. Sorry for this delay.

**Comment by overture8** [comment]
@mickaelpois No worries.

**Comment by mickaelpois** [comment]
@overture8 It will be ok now, new version number is 1.4.3, due to some extra fixes with Travis CI build and NPM auto deployment.
