### ISSUE TITLE
Card Registration

### ISSUE THREAD

**Issue by NicolasSmit** [Mangopay/mangopay2-nodejs-sdk#62]
Hi,
I'm having trouble using `api.CardRegistrations.create(cardRegistration)` : 
Here are the steps : 
1. I'm adding a card with card registration data that I received. This is working well. 
2. Just then, I'm trying to add a new card, but the card registration data are exactly the same than the first one, so I'm getting an error with MangoAPay front-end kit. 

Do you have any idea why this is happening ?

**Comment by gabriellupu** [comment]
Hello @NicolasSmit , can you provide us the HTTP request and the response that is causing the failure and the error message that you receive? Thanks!

**Comment by NicolasSmit** [comment]
Hi @gabriellupu Thanks for you quick answer, here is the error I'm getting :
POST https://api.sandbox.mangopay.com/v2.01/............./CardRegistrations/24252270 400 (Bad Request)
I'm using this package for creating the front registration query :
```
Id:"24252412"
accessKey:"1X0m87dmM2LiwFgxPLBJ"
cardRegistrationURL:"https://homologation-webpayment.payline.com/webpayment/getToken"
preregistrationData:"ctdPU2IGyKn3gQT0GVK0sUxmQEypLk9-Pdz3dphw9_ube37KtHi4c_SaY1dqz2Ak7qGR3aNxrLUiPbx-Z--VxQ"
```

**Comment by gabriellupu** [comment]
Thanks for your reply @NicolasSmit , can you please also provide the Response error message, not just the status? Thanks!

**Comment by NicolasSmit** [comment]
I just had MangoPay's support on phone, they told me that it is not possible to add a second card in the same session, so I have to create a new session to let the user add a 2nd card just after the 1st one. 
I just tried, logging out + logging in lets me add a 2nd card. 

So I can close this issue
Thanks for your help @gabriellupu
