### ISSUE TITLE
how to add user card? 

### ISSUE THREAD

**Issue by uditkumawat** [Mangopay/mangopay2-nodejs-sdk#63]
Hey,
I am using mangoPay node sdk for the first time.I have created sandbox box account.Create card registration object but when I am adding my card ...it is giving some error.

This is my code 
`
const mangopay = require('mangopay2-nodejs-sdk');`
`const MANGO_PAY={
    clientId : PAYMENT_CONFIG.clientId,
    clientPassword : PAYMENT_CONFIG.clientPassword,
    baseUrl : PAYMENT_CONFIG.baseUrl
};

let MANGO_PAY_API = new mangopay(MANGO_PAY);`
`let cardRegistration = {
                "Tag" : "USER",
                "UserId" : customerData.mangoPayId,
                "Currency": CONFIG.APPCONFIG.CURRENCY,
                "CardType" : CONFIG.APPCONFIG.CARD_TYPES.VISA
            };

            MANGO_PAY_API.CardRegistrations.create(cardRegistration).then(function(res){

                let cardRegistrationData={
                    "data": res.PreregistrationData,
                    "accessKeyRef": res.AccessKey,
                    "returnURL": "localhost",
                    "cardNumber": "4970100000000154",
                    "cardExpirationDate": "1020",
                    "cardCvx": "123"
                };

                // Set the headers
                var headers = {
                    'Content-Type': 'application/x-www-form-urlencoded'
                }

                // Configure the request
                var options = {
                    url: res.CardRegistrationURL,
                    headers: headers,
                    form: cardRegistrationData
                }

                console.log(cardRegistrationData)
                console.log(headers)
                console.log(options);

                // 3. POST request to CardRegistrationURL
                MANGO_PAY_API.method('post', function (data, response) {
                    console.log("DATA = %j", data);
                    console.log("RESPONSE = %j", JSON.stringify(response));
                }, options);

                cb();
            })`

I am getting this in respose:

DATA = {"type":"Buffer","data":[101,114,114,111,114,67,111,100,101,61,48,57,49,48,49]}
RESPONSE = [Circular]

What to do with this?

When I am converting into string..it is showing error errorCode=09101

Please help in this issue.

**Comment by gabriellupu** [comment]
@uditkumawat first of all thanks for bringing out this aspect! Can you please let me know if any of [our test cases](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/CardRegistrations.js) covers your issue?

**Comment by gabriellupu** [comment]
Please check [my answer](https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/49#issuecomment-294911599) for #49.
