### ISSUE TITLE
The 3DSecure authentification has failed

### ISSUE THREAD

**Issue by suiko1984** [Mangopay/mangopay2-nodejs-sdk#65]
Hi,

In Sandbox, each of these cards (3569990000000132, 3569990000000157) causes the 3D Secure authentification to fail with the following message. Did I miss something? It seemed to be working a few days ago.
{
  Id: '24446943',
  CreationDate: 1492612438,
  AuthorId: '22457551',
  DebitedFunds: { Currency: 'EUR', Amount: 10678 },
  AuthorizationDate: null,
  Status: 'FAILED',
  PaymentStatus: 'CANCELED',
  ExpirationDate: null,
  PayInId: null,
  ResultCode: '101301',
  ResultMessage: 'Secure mode: The 3DSecure authentication has failed',
  SecureMode: 'DEFAULT',
  CardId: '24001605',
  SecureModeReturnURL: 'https://www.koalap.com/3DSecure?preAuthorizationId=24446943',
  SecureModeRedirectURL: null,
  SecureModeNeeded: true,
  PaymentType: 'CARD',
  ExecutionType: 'DIRECT',
  StatementDescriptor: null }

**Comment by hobailey** [comment]
Hey @suiko1984, our PSP is having a couple of problems with these cards at the moment - you can use 3569990000000165 in the meantime. Sorry for the trouble :-(
