### ISSUE TITLE
Bug in parsing the PayIn getPaymentKey with DirectDebit

### ISSUE THREAD

**Issue by bizarrochris** [Mangopay/mangopay2-nodejs-sdk#66]
When calling PayIns.create with params that include the following:

```JSON
{"AuthorId":xx,
"CreditedUserId":"xx",
"CreditedWalletId":"x","DebitedFunds":{"Currency":"EUR","Amount
":1000},"Fees":{"Currency":"EUR","Amount":100},
"ReturnURL":"http://xxx.xx/xxx","Culture":"de","Tag":"xxx",
"SecureMode":"DEFAULT",
"SecureModeReturnURL":xxx",
"StatementDescriptor":"xx",
"ExecutionDetails": new api.models.PayInExecutionDetailsWeb();
"PaymentDetails": new api.models.PayInPaymentDetailsDirectDebitWeb({
        DirectDebitType: 'SOFORT',
    }),
}
```
does not work and throws an error (TypeError: Cannot read property 'bind' of undefined)

The Problem is that the parsed method is:
payins_directdebit-web-web_create

Which is a problem in: https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/services/PayIns.js#L78

That the web part is passed into the chained string from both the getPaymentKey and the getExecutionKey methods.

I would suggest, to either use only one option: PayInPaymentDetailsDirectDebit without distinguishing between web and direct on the payment details as you already have it on the execution details, or return the string without the  '-web' in both cases.

**Comment by gabriellupu** [comment]
Hello @bizarrochris, thanks for bringing this up. We are currently investigating it and come back with some feedback! 
Thanks!

**Comment by gabriellupu** [comment]
Pull request submitted.

**Comment by bizarrochris** [comment]
awesome!

**Comment by bizarrochris** [comment]
@gabriellupu forgot to ask - when is a release planned, so I can adapt my code to the fix?
