### ISSUE TITLE
Error while adding card

### ISSUE THREAD

**Issue by uditkumawat** [Mangopay/mangopay2-nodejs-sdk#68]
Hi,
When I am adding card of customer after creating customer,I am getting this error - 

Error: getaddrinfo ENOTFOUND api.sandbox.mangopay.com api.sandbox.mangopay.com:443

**Comment by gabriellupu** [comment]
Hello @uditkumawat, can you please provide us snippet of code?

Thanks!

**Comment by uditkumawat** [comment]
some time it works but some time it gives error.
