### ISSUE TITLE
How to deduct amount from customer card?

### ISSUE THREAD

**Issue by uditkumawat** [Mangopay/mangopay2-nodejs-sdk#69]
Hi ,
I have added customer and his card to his profile.
But I am not getting which API to use and deduct some amount from customer card which is added to Mango pay?

It would be great if you provide me the code example of deducting amount from card .
thanks in advance

**Comment by gabriellupu** [comment]
Hello @uditkumawat, you can transfer money from one wallet to the other via [transfers](https://docs.mangopay.com/endpoints/v2/transfers#e224_the-transfer-object).
[Code example in test here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/Transfers.js)

You can also look over [card registrations](https://docs.mangopay.com/endpoints/v2/cards#e177_the-card-registration-object).
[Code example in test here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/CardRegistrations.js)

**Comment by uditkumawat** [comment]
I am planning to make ecommerce website.Customer will sign up in website..he will add card and payment will be deducted from his card.
Is it necessary for the customer to create his wallet ?
To whom that amount will be given?

Seller should also have some wallet in system or it is stored in admin wallet ?

**Comment by hobailey** [comment]
Hi @uditkumawat, I suggest you contact our support team (www.mangopay.com/contact) who'll be able to guide you through the specifics and answer any questions :-)
