### ISSUE TITLE
PayIn needs a PaymentType

### ISSUE THREAD

**Issue by uditkumawat** [Mangopay/mangopay2-nodejs-sdk#70]
Hi,I am trying to make transaction using customer cardId already added to Mango Pay.
My code - 
` let data={

        "AuthorId" : "24704378",
        "CreditedUserId" :"24704378",
        "DebitedFunds" : {"Currency":"EUR","Amount":5000},
        "CreditedWalletId":"24704381",
        "CardId":"24704387",
        "SecureMode":"DEFAULT",
        "SecureModeReturnURL":"http://localhost"
    }`
`MANGO_PAY_API.PayIns.create(data).then(function(data){
        console.log(data);
    },function(err){
        console.log("errr")
        console.log(err);
    })`

Error is coming - "PayIn needs a PaymentType"

Please help in this issue

**Comment by nareeboy** [comment]
im having the same issue. I am adding in PaymentType in the object but it still returns this error
