### ISSUE TITLE
Problem importing sdk in React-Native

### ISSUE THREAD

**Issue by simonthme** [Mangopay/mangopay2-nodejs-sdk#72]
Trying to import the SDK from a React-Native project via npm, though it seems to fail reading directories/files.

<img width="349" alt="capture d ecran 2017-05-11 a 12 42 41" src="https://cloud.githubusercontent.com/assets/17746106/25945584/bb649a20-3647-11e7-9b8b-8d8e73d2a2ee.png">

Is the nodejs mangopay sdk compatible with React-Native?

**Comment by gabriellupu** [comment]
You brought up a interesting issur @simonthme . I will try to reproduce your problem into a react native project. Can you please provide us the code snippet where you do the mangopay import? Thanks

**Comment by simonthme** [comment]
Yes of course! Here is the snippet: 

`import Mangopay from 'mangopay2-nodejs-sdk';

const api = new Mangopay({
 clientId: Constant.mangoId,
 clientPassword: Constant.mangoPwd,
 baseUrl: Constant.mangoUrl
});`

**Comment by mickaelpois** [comment]
Dear @simonthme,
This issue has not been analysed yet, as it is not a high prio one. 
But it's a subject that have been added since May on our backlog, and its priority is getting higher and higher.

I'll keep you posted with any update on it.

Mickaël

**Comment by ignivalancy** [comment]
Mangopay React and React Native First JS Client library with card registration workflow.
https://www.npmjs.com/package/mangopay-client-react

**Comment by paulhristea** [comment]
Hi guys.
Is this still an issue?
