### ISSUE TITLE
Create payout : Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by zevanb** [Mangopay/mangopay2-nodejs-sdk#74]
Hello, 

I'm trying to use the function PayOuts.create but i keep getting the error : 

> Create Payout needs MeanOfPaymentDetails or PaymentType undefined
TypeError: Cannot read property 'bind' of undefined

This is the payout object i'm trying to run :

```
{  
  DebitedWalletId: 27394454,
  MeanOfPaymentDetails: {
    BankAccountId: 27445735,
    BankWireRef: 'invoice 7282'
  },
  PaymentType: 'BANK_WIRE',
  AuthorId: 27394110,
  CreditedUserId: 27394110,
  DebitedFunds: {
    Currency: 'EUR',
    Amount: 8500
  },
  Fees: {
    Currency: 'EUR',
    Amount: 0
  },
  Tag: 'custom meta'
}
```

Am I missing something ?

**Comment by gabriellupu** [comment]
thanks for your feedback @zevanb ! We are looking into it right away!

**Comment by gabriellupu** [comment]
I noticed that you're failure comes from https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/lib/services/PayOuts.js#L49
Curious how come that triggers because I see that you have a `PaymentType` in the JSON provided. Can you please paste the full snippet of code that you are using for creating the PayOut?

Thanks in advance!

**Comment by zevanb** [comment]
Thank you for your help,

I think that the example I saw was outdated. It seems to work well with the payout object :
```
{
  DebitedWalletId: 27394454,
  BankAccountId: 27445735,
  BankWireRef: 'invoice 7282',
  PaymentType: 'BANK_WIRE',
  AuthorId: 27394110,
  CreditedUserId: 27394110,
  DebitedFunds: {
    Currency: 'EUR',
    Amount: 8500
  },
  Fees: {
    Currency: 'EUR',
    Amount: 0
  },
  Tag: 'custom meta'
}
```
 
Apparently there is no use in putting the BankAccountId and the BankWireRef in a MeanOfPaymentDetails object.

**Comment by gabriellupu** [comment]
I'm happy it worked!
