### ISSUE TITLE
Problem to create Kyc Page

### ISSUE THREAD

**Issue by cyboolo** [Mangopay/mangopay2-nodejs-sdk#75]
Does someone could help me to implement CreateKycPage...

I have my user Id (req.params.a below), my document Id (req.params.b below) with status created and my file encoded on base64 (req.params.c below)...

Then I call that function on Nodejs:
`

1
--
Parse.Cloud.define('new_kyc_page_mpay', function (req, res)
  | {
  | var mangopay = require('mangopay2-nodejs-sdk');
  |  
  | var mango = new mangopay({
  | clientId: 'xxx',
  | clientPassword: 'xxx'
  | });
  |  
  | mango.Users.createKycPageFromFile( req.params.a, req.params.b, {
  | "File": req.params.c
  | },function(myKYCpage) {
  | // Output the created user data to console
  | res.success(myKYCpage);
  | });
  |  
  | });

`

And I get 'File does not exist'

I tried the same with CreateKycPage but I just get some empty buffer...

I don't figure out how to create a page with these two methods 'CreateKycPage' and 'CreateKycPageFromFile'... on mangopay docs, code is only in PHP... it seems that the file has to be encoded in base64 but when I see the codes on Nodejs it seems that we have to provide file path and that the library encodes that file

Well I am lost... everything was ok (user, wallet, bank accounts, kyc documents) but I am blocked with this page creation.

Thanks for any help

**Comment by cyboolo** [comment]
I found the solution that maybe is obvious for some of you but was kind of tricky for me as documentation on that point on mangopay site is missing in my point of view... and only php code examples.

Because I couldn't see in that documentation that api calls response to that particular endpoint are empty and you have to catch response statusCode that is 204 so body is empty.

So for those who have the same problem, these are 2 solutions that worked for me:

1 - with mangopay node js library:

```
Parse.Cloud.define('new_page_mpay', function (req, res)
--
  | {
  | var mangopay = require('mangopay2-nodejs-sdk');
  |  
  | var mango = new mangopay({
  | clientId: 'your_client_id',
  | clientPassword: 'passphrase' .  // mode sandbox
  | });
  |  
  | var KycPage = new mango.models.KycPage({
  | "File":req.params.c // your file base64 encoded
  | });
  |  
  | mango.Users.createKycPage(req.params.a,req.params.b,KycPage, function(error, response, body) {
  | res.success(response.statusCode);
  | });
  |  
  | });
```

You get 204 response status if everything is OK and then you have to submit your Kyc document for validation.

2- with post request:

req.params.a is User_id
req.params.b is document_kyc_id
req.params.c is your encoded base64 file


```
var page = { method: 'POST',
--
  | url: 'https://api.sandbox.mangopay.com/v2.01/your_client_id/users/'+req.params.a+'/kyc/documents/'+req.params.b+'/pages/',
  | headers: { 'content-type': 'application/json',
  | "Authorization": "Bearer "+ access_token
  | },
  | body: JSON.stringify({"File":req.params.c}) };
  |  
  | request(page, function (error, response, body) {
  | if(error){res.error(error);}
  | res.success(response.statusCode);
  | });
```

**Comment by mickaelpois** [comment]
Hello @cyboolo 

Thanks for your "auto-answer", I guess it could be very helpful for all node.js devs there!

I'm sorry if our documentation is not clear enough:
- on docs.mangopay.com, we're just giving some PHP code examples, that's right, and we can't give any other language example on it for the moment
- on our node.js documentation, I guess we could be more precise. I will check what's missing very soon, and enhance it ASAP.

Mickaël
