### ISSUE TITLE
Internal server error in Payin using Preauthorization

### ISSUE THREAD

**Issue by foramkumarparekh** [Mangopay/mangopay2-nodejs-sdk#86]
Hi I am creating a PayIn for a preauthorization, but I am getting

> { Message: 'Internal Server Error',
  Type: 'other',
  Id: 'e9e302b2-c544-4285-bd30-9cf95e6d9f82#1505804242',
  Date: 1505804243,
  errors: null }

for the below code:

> let data = {
            "AuthorId": userId,
            "CreditedUserId": userId,
            "CreditedWalletId": walletId,
            "DebitedFunds": {
            "Currency": "GBP",
            "Amount": 1200
            },
            "Fees": {
            "Currency": "GBP",
            "Amount": 00
            },
            "PaymentType": "PREAUTHORIZED",
           "ExecutionType": "DIRECT", 
}
data.ExecutionDetails = new api.models.PayInExecutionDetailsDirect({
            SecureMode: "DEFAULT",
            SecureModeReturnURL: "https://localhost",
            SecureModeRedirectURL: "https://localhost",
            SecureModeNeeded: false
        })
data.PaymentDetails = new api.models.PayInPaymentDetailsPreAuthorized({"PreauthorizationId":preauthId});
let payin = new api.models.PayIn(data);
api.PayIns.create(payin).then(function (response) {
            // Promise function called
            console.log('response')
            console.log(response)
        }, function (error) {
            //exception
            console.log('error in PayIns');
            console.log(error);
        })

Can you tell me what mistake I am making?

**Comment by hobailey** [comment]
Hmm, from looking at the log, looks like your `walletId` is actually an array instead of a string. We're seeing this on our side:
```
{
  "Tag": "event details",
  "AuthorId": "33534144",
  "CreditedUserId": "33534144",
  "CreditedWalletId": ["33534147"],
  "DebitedFunds": {
    "Currency": "GBP",
    "Amount": 1200
  },
  "Fees": {
    "Currency": "GBP",
    "Amount": 0
  },
  "PreauthorizationId": "33744333"
}
```

**Comment by foramkumarparekh** [comment]
Thanks! That worked.
