### ISSUE TITLE
Issue in creating KYC document

### ISSUE THREAD

**Issue by foramkumarparekh** [Mangopay/mangopay2-nodejs-sdk#87]
Hi,

I am trying to create kyc document, but getting

> { Message: 'the body cannot be empty',
  Type: 'empty_body',
  Id: 'a9ea2062-6727-48ac-bff4-5a03287739a6#1505976508',
  Date: 1505976509,
  errors: null }

for the below code

        let kycDoc = {
                        "Type": "IDENTITY_PROOF",
                         "Status": "CREATED",
                        "UserId": users[0].userId
                    }
        let doc = new api.models.KycDocument(kycDoc);
         api.Users.createKycDocument(doc).then(function (response) {
            // Promise function called
            console.log('response')
            console.log(response)
        }, function (error) {
            //exception
            console.log('mangopay service: error in creating kyc');
            console.log(error);
        })

Let me know, what I need to modify to get this code working.

**Comment by foramkumarparekh** [comment]
Any updates on this??

**Comment by paulhristea** [comment]
Hello @foramkumarparekh! Sorry for the wait.

Could you please try sending the `UserId` as the first parameter to the API method?

So something like this:
```
api.Users.createKycDocument(userId, doc).then(function (response) {
    ...
}
```

**Comment by foramkumarparekh** [comment]
Hey, thanks. It worked.
BUt I have one more concern. After creating a page using base64 string, I get a buffer in response. Is it correct?

Also, for updating the status, to validation_asked, do I need to pass an object in, Users.updateKycDocument(userId, kycDocumentId, callback, options) API?

**Comment by paulhristea** [comment]
Great!

As for your latest concerns, could you please post the code that you are using as well? Makes figuring out the issue much easier.

Thanks!

**Comment by paulhristea** [comment]
Great!

As far as I know, the response from uploading a document page is ignorable, as long as the code is 20X.
As for your status update, try sending an object only having the `Status` field, such as:

```
{
    "Status": "VALIDATION_ASKED"
}
```

Thanks!

**Comment by paulhristea** [comment]
Great!

As far as I know, the response from uploading a document page can just be ignored, as long as the code is 20X. That means the page is created ok.

The way to update the status of a KYC Document is usually something like this:
```
    kycDocument.Status = KycDocumentStatus.ValidationAsked;
    api.Users.updateKycDocument(userId, kycDocument).then(function(){
        ...
    }
```
where `kycDocument` is the object that you have retrieved from the server, or created.
Try it out and get back to me with any other issues.

Thanks!
