### ISSUE TITLE
Idempotency support?

### ISSUE THREAD

**Issue by jonathanazulay** [Mangopay/mangopay2-nodejs-sdk#88]
Hello
Is Idempotency-keys supported by the SDK? How do I use it?

**Comment by paulhristea** [comment]
Hello @jonathanazulay!

Unfortunately, right now the Idempotency Key feature is not completely implemented into the NodeJS SDK. However, there is a way to make use of the functionality: try sending an `Idempotency-Key` header (having a unique value of course) with your POST request as follows:
```
var parameters = {
    headers: {
        Idempotency-Key: '1a2b3c4d5e6f7g'
    }
}
api.Users.create(user, parameters).then(function(response) {
    ...
})
```
and then later you can do a GET request on `http://mangopay-base-url/client-id/responses/1a2b3c4d5e6f7g` (using the same key as the one sent as header before) to get the idempotent response. You will have to do the GET request using an HTTP client from your own app, as this is the part which is not implemented yet on our SDK.

Thanks for your interest, please let us know how it works out for you.
Have a great day!
