### ISSUE TITLE
apiMethods wrong variables

### ISSUE THREAD

**Issue by WundrApp** [Mangopay/mangopay2-nodejs-sdk#89]
There is an issue in the apiMethods.js file for the routes : 
- mandates_get_for_user
- mandates_get_for_bank_account

The id parameter is not written as expected : its is {$id}, and should be ${id}

**Comment by mickaelpois** [comment]
Hi @WundrApp,

Thanks for pointing this, #104 will fix it on our next 1.7.0 version which will be released today !

Mickaël
